#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 198
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define PRODUCTION_ID_COUNT 41

enum ts_symbol_identifiers {
  sym_line_comment = 1,
  anon_sym_record = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LBRACK = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACK = 7,
  anon_sym_COLON = 8,
  anon_sym_type = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_SEMI = 12,
  anon_sym_def = 13,
  anon_sym_EQ = 14,
  anon_sym_SLASH = 15,
  anon_sym_interface = 16,
  sym_not_implemented = 17,
  anon_sym_val = 18,
  anon_sym_var = 19,
  sym_number = 20,
  aux_sym_generic_identifier_token1 = 21,
  sym_source_file = 22,
  sym__definition = 23,
  sym_record = 24,
  sym_type_parameters = 25,
  sym_parameters = 26,
  sym_parameter = 27,
  sym_parameter_type = 28,
  sym_type = 29,
  sym_type_members = 30,
  sym_type_member = 31,
  sym_function = 32,
  sym_block_parameters = 33,
  sym_return_type = 34,
  sym_effekts = 35,
  sym_interface = 36,
  sym_interface_methods = 37,
  sym_interface_method = 38,
  sym__expression = 39,
  sym_block = 40,
  aux_sym__block_content = 41,
  sym_statement = 42,
  sym_assignment = 43,
  sym_expression = 44,
  sym_generic_identifier = 45,
  sym_type_identifier = 46,
  sym_identifier = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_type_parameters_repeat1 = 49,
  aux_sym_parameters_repeat1 = 50,
  aux_sym_type_members_repeat1 = 51,
  aux_sym_effekts_repeat1 = 52,
  aux_sym_interface_methods_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_line_comment] = "line_comment",
  [anon_sym_record] = "record",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_type] = "type",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_def] = "def",
  [anon_sym_EQ] = "=",
  [anon_sym_SLASH] = "/",
  [anon_sym_interface] = "interface",
  [sym_not_implemented] = "not_implemented",
  [anon_sym_val] = "val",
  [anon_sym_var] = "var",
  [sym_number] = "number",
  [aux_sym_generic_identifier_token1] = "generic_identifier_token1",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_record] = "record",
  [sym_type_parameters] = "type_parameters",
  [sym_parameters] = "parameters",
  [sym_parameter] = "parameter",
  [sym_parameter_type] = "parameter_type",
  [sym_type] = "type",
  [sym_type_members] = "type_members",
  [sym_type_member] = "type_member",
  [sym_function] = "function",
  [sym_block_parameters] = "block_parameters",
  [sym_return_type] = "return_type",
  [sym_effekts] = "effekts",
  [sym_interface] = "interface",
  [sym_interface_methods] = "interface_methods",
  [sym_interface_method] = "interface_method",
  [sym__expression] = "_expression",
  [sym_block] = "block",
  [aux_sym__block_content] = "_block_content",
  [sym_statement] = "statement",
  [sym_assignment] = "assignment",
  [sym_expression] = "expression",
  [sym_generic_identifier] = "generic_identifier",
  [sym_type_identifier] = "type_identifier",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_type_parameters_repeat1] = "type_parameters_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_type_members_repeat1] = "type_members_repeat1",
  [aux_sym_effekts_repeat1] = "effekts_repeat1",
  [aux_sym_interface_methods_repeat1] = "interface_methods_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_line_comment] = sym_line_comment,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_interface] = anon_sym_interface,
  [sym_not_implemented] = sym_not_implemented,
  [anon_sym_val] = anon_sym_val,
  [anon_sym_var] = anon_sym_var,
  [sym_number] = sym_number,
  [aux_sym_generic_identifier_token1] = aux_sym_generic_identifier_token1,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_record] = sym_record,
  [sym_type_parameters] = sym_type_parameters,
  [sym_parameters] = sym_parameters,
  [sym_parameter] = sym_parameter,
  [sym_parameter_type] = sym_parameter_type,
  [sym_type] = sym_type,
  [sym_type_members] = sym_type_members,
  [sym_type_member] = sym_type_member,
  [sym_function] = sym_function,
  [sym_block_parameters] = sym_block_parameters,
  [sym_return_type] = sym_return_type,
  [sym_effekts] = sym_effekts,
  [sym_interface] = sym_interface,
  [sym_interface_methods] = sym_interface_methods,
  [sym_interface_method] = sym_interface_method,
  [sym__expression] = sym__expression,
  [sym_block] = sym_block,
  [aux_sym__block_content] = aux_sym__block_content,
  [sym_statement] = sym_statement,
  [sym_assignment] = sym_assignment,
  [sym_expression] = sym_expression,
  [sym_generic_identifier] = sym_generic_identifier,
  [sym_type_identifier] = sym_type_identifier,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_type_parameters_repeat1] = aux_sym_type_parameters_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_type_members_repeat1] = aux_sym_type_members_repeat1,
  [aux_sym_effekts_repeat1] = aux_sym_effekts_repeat1,
  [aux_sym_interface_methods_repeat1] = aux_sym_interface_methods_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_interface] = {
    .visible = true,
    .named = false,
  },
  [sym_not_implemented] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_val] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_generic_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_type_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_members] = {
    .visible = true,
    .named = true,
  },
  [sym_type_member] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_block_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_return_type] = {
    .visible = true,
    .named = true,
  },
  [sym_effekts] = {
    .visible = true,
    .named = true,
  },
  [sym_interface] = {
    .visible = true,
    .named = true,
  },
  [sym_interface_methods] = {
    .visible = true,
    .named = true,
  },
  [sym_interface_method] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__block_content] = {
    .visible = false,
    .named = false,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_members_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_effekts_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interface_methods_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block_parameters = 1,
  field_body = 2,
  field_effekts = 3,
  field_kind = 4,
  field_member = 5,
  field_members = 6,
  field_name = 7,
  field_parameters = 8,
  field_return_type = 9,
  field_type_parameters = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block_parameters] = "block_parameters",
  [field_body] = "body",
  [field_effekts] = "effekts",
  [field_kind] = "kind",
  [field_member] = "member",
  [field_members] = "members",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_return_type] = "return_type",
  [field_type_parameters] = "type_parameters",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 1},
  [9] = {.index = 14, .length = 3},
  [10] = {.index = 17, .length = 3},
  [11] = {.index = 20, .length = 3},
  [12] = {.index = 23, .length = 3},
  [13] = {.index = 26, .length = 4},
  [14] = {.index = 30, .length = 4},
  [15] = {.index = 34, .length = 4},
  [16] = {.index = 38, .length = 2},
  [17] = {.index = 40, .length = 2},
  [18] = {.index = 42, .length = 2},
  [19] = {.index = 44, .length = 4},
  [20] = {.index = 48, .length = 4},
  [21] = {.index = 52, .length = 4},
  [22] = {.index = 56, .length = 5},
  [23] = {.index = 61, .length = 2},
  [24] = {.index = 63, .length = 3},
  [25] = {.index = 66, .length = 3},
  [26] = {.index = 69, .length = 3},
  [27] = {.index = 72, .length = 1},
  [28] = {.index = 73, .length = 5},
  [29] = {.index = 78, .length = 5},
  [30] = {.index = 83, .length = 5},
  [31] = {.index = 88, .length = 3},
  [32] = {.index = 91, .length = 3},
  [33] = {.index = 94, .length = 3},
  [34] = {.index = 97, .length = 4},
  [35] = {.index = 101, .length = 1},
  [36] = {.index = 102, .length = 6},
  [37] = {.index = 108, .length = 4},
  [38] = {.index = 112, .length = 4},
  [39] = {.index = 116, .length = 4},
  [40] = {.index = 120, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_members, 3},
    {field_name, 1},
  [3] =
    {field_name, 1},
    {field_parameters, 2},
  [5] =
    {field_kind, 2},
    {field_name, 0},
  [7] =
    {field_members, 4},
    {field_name, 1},
    {field_parameters, 2},
  [10] =
    {field_member, 0},
  [11] =
    {field_body, 5},
    {field_name, 1},
  [13] =
    {field_effekts, 1},
  [14] =
    {field_block_parameters, 4},
    {field_body, 6},
    {field_name, 1},
  [17] =
    {field_body, 6},
    {field_name, 1},
    {field_parameters, 3},
  [20] =
    {field_body, 6},
    {field_name, 1},
    {field_type_parameters, 2},
  [23] =
    {field_body, 7},
    {field_name, 1},
    {field_return_type, 5},
  [26] =
    {field_block_parameters, 5},
    {field_body, 7},
    {field_name, 1},
    {field_parameters, 3},
  [30] =
    {field_block_parameters, 5},
    {field_body, 7},
    {field_name, 1},
    {field_type_parameters, 2},
  [34] =
    {field_body, 7},
    {field_name, 1},
    {field_parameters, 4},
    {field_type_parameters, 2},
  [38] =
    {field_block_parameters, 4},
    {field_name, 1},
  [40] =
    {field_name, 1},
    {field_parameters, 3},
  [42] =
    {field_name, 1},
    {field_type_parameters, 2},
  [44] =
    {field_block_parameters, 4},
    {field_body, 8},
    {field_name, 1},
    {field_return_type, 6},
  [48] =
    {field_body, 8},
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 6},
  [52] =
    {field_body, 8},
    {field_name, 1},
    {field_return_type, 6},
    {field_type_parameters, 2},
  [56] =
    {field_block_parameters, 6},
    {field_body, 8},
    {field_name, 1},
    {field_parameters, 4},
    {field_type_parameters, 2},
  [61] =
    {field_name, 1},
    {field_return_type, 5},
  [63] =
    {field_block_parameters, 5},
    {field_name, 1},
    {field_parameters, 3},
  [66] =
    {field_block_parameters, 5},
    {field_name, 1},
    {field_type_parameters, 2},
  [69] =
    {field_name, 1},
    {field_parameters, 4},
    {field_type_parameters, 2},
  [72] =
    {field_effekts, 4},
  [73] =
    {field_block_parameters, 5},
    {field_body, 9},
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 7},
  [78] =
    {field_block_parameters, 5},
    {field_body, 9},
    {field_name, 1},
    {field_return_type, 7},
    {field_type_parameters, 2},
  [83] =
    {field_body, 9},
    {field_name, 1},
    {field_parameters, 4},
    {field_return_type, 7},
    {field_type_parameters, 2},
  [88] =
    {field_block_parameters, 4},
    {field_name, 1},
    {field_return_type, 6},
  [91] =
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 6},
  [94] =
    {field_name, 1},
    {field_return_type, 6},
    {field_type_parameters, 2},
  [97] =
    {field_block_parameters, 6},
    {field_name, 1},
    {field_parameters, 4},
    {field_type_parameters, 2},
  [101] =
    {field_effekts, 5},
  [102] =
    {field_block_parameters, 6},
    {field_body, 10},
    {field_name, 1},
    {field_parameters, 4},
    {field_return_type, 8},
    {field_type_parameters, 2},
  [108] =
    {field_block_parameters, 5},
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 7},
  [112] =
    {field_block_parameters, 5},
    {field_name, 1},
    {field_return_type, 7},
    {field_type_parameters, 2},
  [116] =
    {field_name, 1},
    {field_parameters, 4},
    {field_return_type, 7},
    {field_type_parameters, 2},
  [120] =
    {field_block_parameters, 6},
    {field_name, 1},
    {field_parameters, 4},
    {field_return_type, 8},
    {field_type_parameters, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
  [161] = 161,
  [162] = 162,
  [163] = 163,
  [164] = 164,
  [165] = 165,
  [166] = 166,
  [167] = 167,
  [168] = 168,
  [169] = 169,
  [170] = 170,
  [171] = 171,
  [172] = 172,
  [173] = 173,
  [174] = 174,
  [175] = 175,
  [176] = 176,
  [177] = 177,
  [178] = 178,
  [179] = 179,
  [180] = 180,
  [181] = 181,
  [182] = 182,
  [183] = 183,
  [184] = 184,
  [185] = 185,
  [186] = 186,
  [187] = 187,
  [188] = 188,
  [189] = 189,
  [190] = 190,
  [191] = 191,
  [192] = 192,
  [193] = 193,
  [194] = 194,
  [195] = 195,
  [196] = 196,
  [197] = 197,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '(', 29,
        ')', 30,
        ',', 32,
        '/', 42,
        ':', 34,
        ';', 38,
        '<', 4,
        '=', 40,
        '[', 31,
        ']', 33,
        'd', 10,
        'i', 18,
        'r', 11,
        't', 24,
        'v', 5,
        '{', 36,
        '}', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '(', 29,
        ')', 30,
        ',', 32,
        '/', 41,
        '=', 40,
        '[', 31,
        'd', 10,
        '{', 36,
        '}', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(30);
      if (lookahead == '}') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(39);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(6);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(45);
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 24:
      if (lookahead == 'y') ADVANCE(20);
      END_STATE();
    case 25:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '/', 3,
        '<', 4,
        'd', 10,
        'i', 18,
        'r', 11,
        't', 24,
        'v', 5,
        '{', 36,
        '}', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_interface);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_not_implemented);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_val);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_generic_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 25},
  [2] = {.lex_state = 25},
  [3] = {.lex_state = 25},
  [4] = {.lex_state = 25},
  [5] = {.lex_state = 25},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 25},
  [11] = {.lex_state = 25},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 25},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 25},
  [16] = {.lex_state = 25},
  [17] = {.lex_state = 25},
  [18] = {.lex_state = 25},
  [19] = {.lex_state = 25},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 25},
  [22] = {.lex_state = 25},
  [23] = {.lex_state = 25},
  [24] = {.lex_state = 25},
  [25] = {.lex_state = 25},
  [26] = {.lex_state = 25},
  [27] = {.lex_state = 25},
  [28] = {.lex_state = 25},
  [29] = {.lex_state = 25},
  [30] = {.lex_state = 25},
  [31] = {.lex_state = 25},
  [32] = {.lex_state = 25},
  [33] = {.lex_state = 25},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 25},
  [36] = {.lex_state = 25},
  [37] = {.lex_state = 25},
  [38] = {.lex_state = 25},
  [39] = {.lex_state = 25},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 2},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 2},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 2},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 2},
  [122] = {.lex_state = 2},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 2},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 2},
  [133] = {.lex_state = 2},
  [134] = {.lex_state = 2},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 2},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 2},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 2},
  [145] = {.lex_state = 2},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 2},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 2},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 2},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 0},
  [158] = {.lex_state = 2},
  [159] = {.lex_state = 2},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 2},
  [162] = {.lex_state = 0},
  [163] = {.lex_state = 0},
  [164] = {.lex_state = 0},
  [165] = {.lex_state = 2},
  [166] = {.lex_state = 0},
  [167] = {.lex_state = 2},
  [168] = {.lex_state = 2},
  [169] = {.lex_state = 0},
  [170] = {.lex_state = 0},
  [171] = {.lex_state = 0},
  [172] = {.lex_state = 0},
  [173] = {.lex_state = 0},
  [174] = {.lex_state = 0},
  [175] = {.lex_state = 0},
  [176] = {.lex_state = 0},
  [177] = {.lex_state = 0},
  [178] = {.lex_state = 0},
  [179] = {.lex_state = 0},
  [180] = {.lex_state = 0},
  [181] = {.lex_state = 0},
  [182] = {.lex_state = 0},
  [183] = {.lex_state = 0},
  [184] = {.lex_state = 0},
  [185] = {.lex_state = 0},
  [186] = {.lex_state = 0},
  [187] = {.lex_state = 0},
  [188] = {.lex_state = 0},
  [189] = {.lex_state = 0},
  [190] = {.lex_state = 0},
  [191] = {.lex_state = 0},
  [192] = {.lex_state = 0},
  [193] = {.lex_state = 0},
  [194] = {.lex_state = 0},
  [195] = {.lex_state = 0},
  [196] = {.lex_state = 0},
  [197] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_interface] = ACTIONS(1),
    [sym_not_implemented] = ACTIONS(1),
    [anon_sym_val] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(178),
    [sym__definition] = STATE(5),
    [sym_record] = STATE(5),
    [sym_type] = STATE(5),
    [sym_function] = STATE(5),
    [sym_interface] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [anon_sym_record] = ACTIONS(7),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_def] = ACTIONS(11),
    [anon_sym_interface] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym_line_comment,
    ACTIONS(20), 1,
      anon_sym_record,
    ACTIONS(23), 1,
      anon_sym_type,
    ACTIONS(26), 1,
      anon_sym_def,
    ACTIONS(29), 1,
      anon_sym_interface,
    STATE(2), 6,
      sym__definition,
      sym_record,
      sym_type,
      sym_function,
      sym_interface,
      aux_sym_source_file_repeat1,
  [27] = 1,
    ACTIONS(32), 12,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_interface,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [42] = 1,
    ACTIONS(34), 12,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_interface,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [57] = 7,
    ACTIONS(7), 1,
      anon_sym_record,
    ACTIONS(9), 1,
      anon_sym_type,
    ACTIONS(11), 1,
      anon_sym_def,
    ACTIONS(13), 1,
      anon_sym_interface,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      sym_line_comment,
    STATE(2), 6,
      sym__definition,
      sym_record,
      sym_type,
      sym_function,
      sym_interface,
      aux_sym_source_file_repeat1,
  [84] = 6,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      sym_assignment,
    ACTIONS(44), 2,
      sym_not_implemented,
      sym_number,
    ACTIONS(46), 2,
      anon_sym_val,
      anon_sym_var,
    STATE(7), 4,
      sym__expression,
      sym_block,
      aux_sym__block_content,
      sym_statement,
  [108] = 6,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      sym_assignment,
    ACTIONS(46), 2,
      anon_sym_val,
      anon_sym_var,
    ACTIONS(50), 2,
      sym_not_implemented,
      sym_number,
    STATE(8), 4,
      sym__expression,
      sym_block,
      aux_sym__block_content,
      sym_statement,
  [132] = 6,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      sym_assignment,
    ACTIONS(57), 2,
      sym_not_implemented,
      sym_number,
    ACTIONS(60), 2,
      anon_sym_val,
      anon_sym_var,
    STATE(8), 4,
      sym__expression,
      sym_block,
      aux_sym__block_content,
      sym_statement,
  [156] = 1,
    ACTIONS(63), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_EQ,
      anon_sym_SLASH,
  [168] = 1,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [177] = 1,
    ACTIONS(67), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [186] = 1,
    ACTIONS(69), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [195] = 1,
    ACTIONS(71), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [204] = 4,
    ACTIONS(73), 1,
      anon_sym_LBRACK,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    STATE(103), 1,
      sym_effekts,
    ACTIONS(75), 3,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_EQ,
  [219] = 1,
    ACTIONS(79), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [228] = 1,
    ACTIONS(81), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [237] = 1,
    ACTIONS(83), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [246] = 1,
    ACTIONS(85), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [255] = 1,
    ACTIONS(87), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [264] = 1,
    ACTIONS(89), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [273] = 1,
    ACTIONS(91), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [282] = 1,
    ACTIONS(93), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [291] = 1,
    ACTIONS(95), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [300] = 1,
    ACTIONS(97), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [309] = 1,
    ACTIONS(99), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [318] = 1,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [327] = 1,
    ACTIONS(103), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [336] = 1,
    ACTIONS(105), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [345] = 1,
    ACTIONS(107), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [354] = 1,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [363] = 1,
    ACTIONS(111), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [372] = 1,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [381] = 1,
    ACTIONS(115), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [390] = 1,
    ACTIONS(117), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [399] = 1,
    ACTIONS(119), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [408] = 1,
    ACTIONS(121), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [417] = 1,
    ACTIONS(123), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [426] = 1,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [435] = 1,
    ACTIONS(127), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [444] = 5,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    STATE(82), 1,
      sym_parameter,
    STATE(176), 1,
      sym_parameters,
    STATE(185), 1,
      sym_identifier,
  [460] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 2,
      sym_not_implemented,
      sym_number,
    STATE(11), 2,
      sym__expression,
      sym_block,
  [472] = 4,
    ACTIONS(135), 1,
      anon_sym_COLON,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    STATE(115), 1,
      sym_block_parameters,
    ACTIONS(139), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [486] = 5,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym_parameter,
    STATE(173), 1,
      sym_parameters,
    STATE(185), 1,
      sym_identifier,
  [502] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(143), 2,
      sym_not_implemented,
      sym_number,
    STATE(17), 2,
      sym__expression,
      sym_block,
  [514] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(145), 2,
      sym_not_implemented,
      sym_number,
    STATE(21), 2,
      sym__expression,
      sym_block,
  [526] = 4,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    STATE(118), 1,
      sym_parameter,
    STATE(185), 1,
      sym_identifier,
    ACTIONS(147), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [540] = 3,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    STATE(96), 1,
      sym_effekts,
    ACTIONS(149), 3,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_EQ,
  [552] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(151), 2,
      sym_not_implemented,
      sym_number,
    STATE(22), 2,
      sym__expression,
      sym_block,
  [564] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(153), 2,
      sym_not_implemented,
      sym_number,
    STATE(32), 2,
      sym__expression,
      sym_block,
  [576] = 5,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(155), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym_parameter,
    STATE(181), 1,
      sym_parameters,
    STATE(185), 1,
      sym_identifier,
  [592] = 5,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(129), 1,
      sym_type_member,
    STATE(187), 1,
      sym_type_members,
    STATE(189), 1,
      sym_type_identifier,
  [608] = 4,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      anon_sym_COLON,
    STATE(112), 1,
      sym_block_parameters,
    ACTIONS(163), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [622] = 3,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    STATE(109), 1,
      sym_effekts,
    ACTIONS(165), 3,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_EQ,
  [634] = 5,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym_parameter,
    STATE(185), 1,
      sym_identifier,
    STATE(193), 1,
      sym_parameters,
  [650] = 5,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym_parameter,
    STATE(185), 1,
      sym_identifier,
    STATE(190), 1,
      sym_parameters,
  [666] = 4,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(171), 1,
      anon_sym_COLON,
    STATE(98), 1,
      sym_block_parameters,
    ACTIONS(173), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [680] = 5,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym_parameter,
    STATE(185), 1,
      sym_identifier,
    STATE(188), 1,
      sym_parameters,
  [696] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(177), 2,
      sym_not_implemented,
      sym_number,
    STATE(23), 2,
      sym__expression,
      sym_block,
  [708] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(179), 2,
      sym_not_implemented,
      sym_number,
    STATE(13), 2,
      sym__expression,
      sym_block,
  [720] = 4,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      anon_sym_COLON,
    STATE(89), 1,
      sym_block_parameters,
    ACTIONS(183), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [734] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 2,
      sym_not_implemented,
      sym_number,
    STATE(28), 2,
      sym__expression,
      sym_block,
  [746] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(187), 2,
      sym_not_implemented,
      sym_number,
    STATE(25), 2,
      sym__expression,
      sym_block,
  [758] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(189), 2,
      sym_not_implemented,
      sym_number,
    STATE(16), 2,
      sym__expression,
      sym_block,
  [770] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(191), 2,
      sym_not_implemented,
      sym_number,
    STATE(35), 2,
      sym__expression,
      sym_block,
  [782] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(193), 2,
      sym_not_implemented,
      sym_number,
    STATE(30), 2,
      sym__expression,
      sym_block,
  [794] = 5,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(195), 1,
      anon_sym_RBRACE,
    STATE(129), 1,
      sym_type_member,
    STATE(184), 1,
      sym_type_members,
    STATE(189), 1,
      sym_type_identifier,
  [810] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(197), 2,
      sym_not_implemented,
      sym_number,
    STATE(10), 2,
      sym__expression,
      sym_block,
  [822] = 4,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    STATE(118), 1,
      sym_parameter,
    STATE(185), 1,
      sym_identifier,
    ACTIONS(199), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [836] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(201), 2,
      sym_not_implemented,
      sym_number,
    STATE(18), 2,
      sym__expression,
      sym_block,
  [848] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(203), 2,
      sym_not_implemented,
      sym_number,
    STATE(39), 2,
      sym__expression,
      sym_block,
  [860] = 5,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym_parameter,
    STATE(185), 1,
      sym_identifier,
    STATE(191), 1,
      sym_parameters,
  [876] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(207), 2,
      sym_not_implemented,
      sym_number,
    STATE(27), 2,
      sym__expression,
      sym_block,
  [888] = 4,
    ACTIONS(209), 1,
      anon_sym_RBRACE,
    ACTIONS(211), 1,
      anon_sym_def,
    STATE(194), 1,
      sym_interface_methods,
    STATE(87), 2,
      sym_interface_method,
      aux_sym_interface_methods_repeat1,
  [902] = 2,
    ACTIONS(215), 1,
      anon_sym_LBRACK,
    ACTIONS(213), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [911] = 3,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(217), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [922] = 3,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    ACTIONS(224), 1,
      anon_sym_def,
    STATE(76), 2,
      sym_interface_method,
      aux_sym_interface_methods_repeat1,
  [933] = 4,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(227), 1,
      anon_sym_COLON,
    ACTIONS(229), 1,
      anon_sym_EQ,
    STATE(152), 1,
      sym_block_parameters,
  [946] = 1,
    ACTIONS(231), 4,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_EQ,
  [953] = 4,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(233), 1,
      anon_sym_COLON,
    ACTIONS(235), 1,
      anon_sym_EQ,
    STATE(147), 1,
      sym_block_parameters,
  [966] = 4,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(237), 1,
      anon_sym_COLON,
    ACTIONS(239), 1,
      anon_sym_EQ,
    STATE(146), 1,
      sym_block_parameters,
  [979] = 4,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    STATE(82), 1,
      sym_parameter,
    STATE(185), 1,
      sym_identifier,
    STATE(196), 1,
      sym_parameters,
  [992] = 3,
    ACTIONS(243), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(241), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1003] = 3,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(245), 1,
      sym_number,
    STATE(34), 2,
      sym_block,
      sym_expression,
  [1014] = 1,
    ACTIONS(247), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COLON,
      anon_sym_EQ,
  [1021] = 3,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(147), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1032] = 4,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(251), 1,
      anon_sym_COLON,
    ACTIONS(253), 1,
      anon_sym_EQ,
    STATE(164), 1,
      sym_block_parameters,
  [1045] = 3,
    ACTIONS(211), 1,
      anon_sym_def,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
    STATE(76), 2,
      sym_interface_method,
      aux_sym_interface_methods_repeat1,
  [1056] = 1,
    ACTIONS(257), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1062] = 2,
    ACTIONS(259), 1,
      anon_sym_COLON,
    ACTIONS(261), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1070] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(139), 1,
      sym_return_type,
  [1080] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(183), 1,
      sym_return_type,
  [1090] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(182), 1,
      sym_return_type,
  [1100] = 3,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
    STATE(93), 1,
      aux_sym_effekts_repeat1,
  [1110] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(172), 1,
      sym_return_type,
  [1120] = 1,
    ACTIONS(268), 3,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_EQ,
  [1126] = 1,
    ACTIONS(270), 3,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_EQ,
  [1132] = 3,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    STATE(118), 1,
      sym_parameter,
    STATE(185), 1,
      sym_identifier,
  [1142] = 2,
    ACTIONS(272), 1,
      anon_sym_COLON,
    ACTIONS(274), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1150] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(141), 1,
      sym_return_type,
  [1160] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(142), 1,
      sym_return_type,
  [1170] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(143), 1,
      sym_return_type,
  [1180] = 3,
    ACTIONS(276), 1,
      anon_sym_LPAREN,
    ACTIONS(278), 1,
      anon_sym_LBRACK,
    STATE(174), 1,
      sym_type_parameters,
  [1190] = 1,
    ACTIONS(280), 3,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_EQ,
  [1196] = 3,
    ACTIONS(278), 1,
      anon_sym_LBRACK,
    ACTIONS(282), 1,
      anon_sym_LBRACE,
    STATE(179), 1,
      sym_type_parameters,
  [1206] = 3,
    ACTIONS(278), 1,
      anon_sym_LBRACK,
    ACTIONS(284), 1,
      anon_sym_LPAREN,
    STATE(180), 1,
      sym_type_parameters,
  [1216] = 3,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
    STATE(93), 1,
      aux_sym_effekts_repeat1,
  [1226] = 3,
    ACTIONS(290), 1,
      anon_sym_RBRACE,
    ACTIONS(292), 1,
      anon_sym_SEMI,
    STATE(107), 1,
      aux_sym_type_members_repeat1,
  [1236] = 1,
    ACTIONS(295), 3,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_EQ,
  [1242] = 1,
    ACTIONS(297), 3,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_EQ,
  [1248] = 3,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(302), 1,
      anon_sym_RBRACK,
    STATE(110), 1,
      aux_sym_type_parameters_repeat1,
  [1258] = 1,
    ACTIONS(304), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1264] = 2,
    ACTIONS(306), 1,
      anon_sym_COLON,
    ACTIONS(308), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1272] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(195), 1,
      sym_return_type,
  [1282] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(154), 1,
      sym_return_type,
  [1292] = 2,
    ACTIONS(310), 1,
      anon_sym_COLON,
    ACTIONS(312), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1300] = 1,
    ACTIONS(314), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1306] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(170), 1,
      sym_return_type,
  [1316] = 1,
    ACTIONS(217), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1322] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(197), 1,
      sym_return_type,
  [1332] = 3,
    ACTIONS(278), 1,
      anon_sym_LBRACK,
    ACTIONS(316), 1,
      anon_sym_LPAREN,
    STATE(169), 1,
      sym_type_parameters,
  [1342] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(156), 1,
      sym_return_type,
  [1352] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(157), 1,
      sym_return_type,
  [1362] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(320), 1,
      anon_sym_RBRACK,
    STATE(135), 1,
      aux_sym_type_parameters_repeat1,
  [1372] = 3,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(322), 1,
      anon_sym_RBRACE,
    STATE(106), 1,
      aux_sym_effekts_repeat1,
  [1382] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(324), 1,
      anon_sym_RBRACK,
    STATE(130), 1,
      aux_sym_type_parameters_repeat1,
  [1392] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(192), 1,
      sym_return_type,
  [1402] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(326), 1,
      anon_sym_RBRACK,
    STATE(128), 1,
      aux_sym_type_parameters_repeat1,
  [1412] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(328), 1,
      anon_sym_RBRACK,
    STATE(110), 1,
      aux_sym_type_parameters_repeat1,
  [1422] = 3,
    ACTIONS(330), 1,
      anon_sym_RBRACE,
    ACTIONS(332), 1,
      anon_sym_SEMI,
    STATE(131), 1,
      aux_sym_type_members_repeat1,
  [1432] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(334), 1,
      anon_sym_RBRACK,
    STATE(110), 1,
      aux_sym_type_parameters_repeat1,
  [1442] = 3,
    ACTIONS(332), 1,
      anon_sym_SEMI,
    ACTIONS(336), 1,
      anon_sym_RBRACE,
    STATE(107), 1,
      aux_sym_type_members_repeat1,
  [1452] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(163), 1,
      sym_type_member,
    STATE(189), 1,
      sym_type_identifier,
  [1462] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(162), 1,
      sym_return_type,
  [1472] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(14), 1,
      sym_type_identifier,
    STATE(175), 1,
      sym_return_type,
  [1482] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(338), 1,
      anon_sym_RBRACK,
    STATE(110), 1,
      aux_sym_type_parameters_repeat1,
  [1492] = 3,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(74), 1,
      sym_type_identifier,
    STATE(116), 1,
      sym_parameter_type,
  [1502] = 1,
    ACTIONS(340), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1507] = 2,
    ACTIONS(342), 1,
      aux_sym_generic_identifier_token1,
    STATE(127), 1,
      sym_generic_identifier,
  [1514] = 1,
    ACTIONS(344), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1519] = 1,
    ACTIONS(346), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1524] = 1,
    ACTIONS(348), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1529] = 1,
    ACTIONS(350), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1534] = 1,
    ACTIONS(352), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1539] = 2,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(104), 1,
      sym_type_identifier,
  [1546] = 2,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    STATE(120), 1,
      sym_identifier,
  [1553] = 2,
    ACTIONS(354), 1,
      anon_sym_COLON,
    ACTIONS(356), 1,
      anon_sym_EQ,
  [1560] = 2,
    ACTIONS(358), 1,
      anon_sym_COLON,
    ACTIONS(360), 1,
      anon_sym_EQ,
  [1567] = 1,
    ACTIONS(266), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1572] = 2,
    ACTIONS(342), 1,
      aux_sym_generic_identifier_token1,
    STATE(125), 1,
      sym_generic_identifier,
  [1579] = 1,
    ACTIONS(362), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1584] = 2,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(124), 1,
      sym_type_identifier,
  [1591] = 2,
    ACTIONS(364), 1,
      anon_sym_COLON,
    ACTIONS(366), 1,
      anon_sym_EQ,
  [1598] = 2,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(102), 1,
      sym_type_identifier,
  [1605] = 1,
    ACTIONS(368), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1610] = 1,
    ACTIONS(370), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1615] = 1,
    ACTIONS(372), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1620] = 1,
    ACTIONS(374), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1625] = 2,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    STATE(105), 1,
      sym_identifier,
  [1632] = 2,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(171), 1,
      sym_type_identifier,
  [1639] = 1,
    ACTIONS(376), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1644] = 2,
    ACTIONS(131), 1,
      aux_sym_generic_identifier_token1,
    STATE(186), 1,
      sym_identifier,
  [1651] = 1,
    ACTIONS(378), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1656] = 1,
    ACTIONS(290), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1661] = 2,
    ACTIONS(380), 1,
      anon_sym_COLON,
    ACTIONS(382), 1,
      anon_sym_EQ,
  [1668] = 2,
    ACTIONS(342), 1,
      aux_sym_generic_identifier_token1,
    STATE(123), 1,
      sym_generic_identifier,
  [1675] = 1,
    ACTIONS(302), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1680] = 2,
    ACTIONS(342), 1,
      aux_sym_generic_identifier_token1,
    STATE(166), 1,
      sym_generic_identifier,
  [1687] = 2,
    ACTIONS(159), 1,
      aux_sym_generic_identifier_token1,
    STATE(148), 1,
      sym_type_identifier,
  [1694] = 1,
    ACTIONS(384), 1,
      anon_sym_LPAREN,
  [1698] = 1,
    ACTIONS(386), 1,
      anon_sym_EQ,
  [1702] = 1,
    ACTIONS(388), 1,
      anon_sym_LBRACE,
  [1706] = 1,
    ACTIONS(390), 1,
      anon_sym_EQ,
  [1710] = 1,
    ACTIONS(392), 1,
      anon_sym_RPAREN,
  [1714] = 1,
    ACTIONS(394), 1,
      anon_sym_LPAREN,
  [1718] = 1,
    ACTIONS(396), 1,
      anon_sym_EQ,
  [1722] = 1,
    ACTIONS(398), 1,
      anon_sym_RPAREN,
  [1726] = 1,
    ACTIONS(400), 1,
      anon_sym_LBRACE,
  [1730] = 1,
    ACTIONS(402), 1,
      ts_builtin_sym_end,
  [1734] = 1,
    ACTIONS(404), 1,
      anon_sym_LBRACE,
  [1738] = 1,
    ACTIONS(406), 1,
      anon_sym_LPAREN,
  [1742] = 1,
    ACTIONS(408), 1,
      anon_sym_RPAREN,
  [1746] = 1,
    ACTIONS(410), 1,
      anon_sym_EQ,
  [1750] = 1,
    ACTIONS(412), 1,
      anon_sym_EQ,
  [1754] = 1,
    ACTIONS(414), 1,
      anon_sym_RBRACE,
  [1758] = 1,
    ACTIONS(416), 1,
      anon_sym_COLON,
  [1762] = 1,
    ACTIONS(418), 1,
      anon_sym_EQ,
  [1766] = 1,
    ACTIONS(420), 1,
      anon_sym_RBRACE,
  [1770] = 1,
    ACTIONS(422), 1,
      anon_sym_RPAREN,
  [1774] = 1,
    ACTIONS(424), 1,
      anon_sym_LPAREN,
  [1778] = 1,
    ACTIONS(426), 1,
      anon_sym_RPAREN,
  [1782] = 1,
    ACTIONS(428), 1,
      anon_sym_RPAREN,
  [1786] = 1,
    ACTIONS(430), 1,
      anon_sym_EQ,
  [1790] = 1,
    ACTIONS(432), 1,
      anon_sym_RPAREN,
  [1794] = 1,
    ACTIONS(434), 1,
      anon_sym_RBRACE,
  [1798] = 1,
    ACTIONS(436), 1,
      anon_sym_EQ,
  [1802] = 1,
    ACTIONS(438), 1,
      anon_sym_RBRACE,
  [1806] = 1,
    ACTIONS(440), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 42,
  [SMALL_STATE(5)] = 57,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 108,
  [SMALL_STATE(8)] = 132,
  [SMALL_STATE(9)] = 156,
  [SMALL_STATE(10)] = 168,
  [SMALL_STATE(11)] = 177,
  [SMALL_STATE(12)] = 186,
  [SMALL_STATE(13)] = 195,
  [SMALL_STATE(14)] = 204,
  [SMALL_STATE(15)] = 219,
  [SMALL_STATE(16)] = 228,
  [SMALL_STATE(17)] = 237,
  [SMALL_STATE(18)] = 246,
  [SMALL_STATE(19)] = 255,
  [SMALL_STATE(20)] = 264,
  [SMALL_STATE(21)] = 273,
  [SMALL_STATE(22)] = 282,
  [SMALL_STATE(23)] = 291,
  [SMALL_STATE(24)] = 300,
  [SMALL_STATE(25)] = 309,
  [SMALL_STATE(26)] = 318,
  [SMALL_STATE(27)] = 327,
  [SMALL_STATE(28)] = 336,
  [SMALL_STATE(29)] = 345,
  [SMALL_STATE(30)] = 354,
  [SMALL_STATE(31)] = 363,
  [SMALL_STATE(32)] = 372,
  [SMALL_STATE(33)] = 381,
  [SMALL_STATE(34)] = 390,
  [SMALL_STATE(35)] = 399,
  [SMALL_STATE(36)] = 408,
  [SMALL_STATE(37)] = 417,
  [SMALL_STATE(38)] = 426,
  [SMALL_STATE(39)] = 435,
  [SMALL_STATE(40)] = 444,
  [SMALL_STATE(41)] = 460,
  [SMALL_STATE(42)] = 472,
  [SMALL_STATE(43)] = 486,
  [SMALL_STATE(44)] = 502,
  [SMALL_STATE(45)] = 514,
  [SMALL_STATE(46)] = 526,
  [SMALL_STATE(47)] = 540,
  [SMALL_STATE(48)] = 552,
  [SMALL_STATE(49)] = 564,
  [SMALL_STATE(50)] = 576,
  [SMALL_STATE(51)] = 592,
  [SMALL_STATE(52)] = 608,
  [SMALL_STATE(53)] = 622,
  [SMALL_STATE(54)] = 634,
  [SMALL_STATE(55)] = 650,
  [SMALL_STATE(56)] = 666,
  [SMALL_STATE(57)] = 680,
  [SMALL_STATE(58)] = 696,
  [SMALL_STATE(59)] = 708,
  [SMALL_STATE(60)] = 720,
  [SMALL_STATE(61)] = 734,
  [SMALL_STATE(62)] = 746,
  [SMALL_STATE(63)] = 758,
  [SMALL_STATE(64)] = 770,
  [SMALL_STATE(65)] = 782,
  [SMALL_STATE(66)] = 794,
  [SMALL_STATE(67)] = 810,
  [SMALL_STATE(68)] = 822,
  [SMALL_STATE(69)] = 836,
  [SMALL_STATE(70)] = 848,
  [SMALL_STATE(71)] = 860,
  [SMALL_STATE(72)] = 876,
  [SMALL_STATE(73)] = 888,
  [SMALL_STATE(74)] = 902,
  [SMALL_STATE(75)] = 911,
  [SMALL_STATE(76)] = 922,
  [SMALL_STATE(77)] = 933,
  [SMALL_STATE(78)] = 946,
  [SMALL_STATE(79)] = 953,
  [SMALL_STATE(80)] = 966,
  [SMALL_STATE(81)] = 979,
  [SMALL_STATE(82)] = 992,
  [SMALL_STATE(83)] = 1003,
  [SMALL_STATE(84)] = 1014,
  [SMALL_STATE(85)] = 1021,
  [SMALL_STATE(86)] = 1032,
  [SMALL_STATE(87)] = 1045,
  [SMALL_STATE(88)] = 1056,
  [SMALL_STATE(89)] = 1062,
  [SMALL_STATE(90)] = 1070,
  [SMALL_STATE(91)] = 1080,
  [SMALL_STATE(92)] = 1090,
  [SMALL_STATE(93)] = 1100,
  [SMALL_STATE(94)] = 1110,
  [SMALL_STATE(95)] = 1120,
  [SMALL_STATE(96)] = 1126,
  [SMALL_STATE(97)] = 1132,
  [SMALL_STATE(98)] = 1142,
  [SMALL_STATE(99)] = 1150,
  [SMALL_STATE(100)] = 1160,
  [SMALL_STATE(101)] = 1170,
  [SMALL_STATE(102)] = 1180,
  [SMALL_STATE(103)] = 1190,
  [SMALL_STATE(104)] = 1196,
  [SMALL_STATE(105)] = 1206,
  [SMALL_STATE(106)] = 1216,
  [SMALL_STATE(107)] = 1226,
  [SMALL_STATE(108)] = 1236,
  [SMALL_STATE(109)] = 1242,
  [SMALL_STATE(110)] = 1248,
  [SMALL_STATE(111)] = 1258,
  [SMALL_STATE(112)] = 1264,
  [SMALL_STATE(113)] = 1272,
  [SMALL_STATE(114)] = 1282,
  [SMALL_STATE(115)] = 1292,
  [SMALL_STATE(116)] = 1300,
  [SMALL_STATE(117)] = 1306,
  [SMALL_STATE(118)] = 1316,
  [SMALL_STATE(119)] = 1322,
  [SMALL_STATE(120)] = 1332,
  [SMALL_STATE(121)] = 1342,
  [SMALL_STATE(122)] = 1352,
  [SMALL_STATE(123)] = 1362,
  [SMALL_STATE(124)] = 1372,
  [SMALL_STATE(125)] = 1382,
  [SMALL_STATE(126)] = 1392,
  [SMALL_STATE(127)] = 1402,
  [SMALL_STATE(128)] = 1412,
  [SMALL_STATE(129)] = 1422,
  [SMALL_STATE(130)] = 1432,
  [SMALL_STATE(131)] = 1442,
  [SMALL_STATE(132)] = 1452,
  [SMALL_STATE(133)] = 1462,
  [SMALL_STATE(134)] = 1472,
  [SMALL_STATE(135)] = 1482,
  [SMALL_STATE(136)] = 1492,
  [SMALL_STATE(137)] = 1502,
  [SMALL_STATE(138)] = 1507,
  [SMALL_STATE(139)] = 1514,
  [SMALL_STATE(140)] = 1519,
  [SMALL_STATE(141)] = 1524,
  [SMALL_STATE(142)] = 1529,
  [SMALL_STATE(143)] = 1534,
  [SMALL_STATE(144)] = 1539,
  [SMALL_STATE(145)] = 1546,
  [SMALL_STATE(146)] = 1553,
  [SMALL_STATE(147)] = 1560,
  [SMALL_STATE(148)] = 1567,
  [SMALL_STATE(149)] = 1572,
  [SMALL_STATE(150)] = 1579,
  [SMALL_STATE(151)] = 1584,
  [SMALL_STATE(152)] = 1591,
  [SMALL_STATE(153)] = 1598,
  [SMALL_STATE(154)] = 1605,
  [SMALL_STATE(155)] = 1610,
  [SMALL_STATE(156)] = 1615,
  [SMALL_STATE(157)] = 1620,
  [SMALL_STATE(158)] = 1625,
  [SMALL_STATE(159)] = 1632,
  [SMALL_STATE(160)] = 1639,
  [SMALL_STATE(161)] = 1644,
  [SMALL_STATE(162)] = 1651,
  [SMALL_STATE(163)] = 1656,
  [SMALL_STATE(164)] = 1661,
  [SMALL_STATE(165)] = 1668,
  [SMALL_STATE(166)] = 1675,
  [SMALL_STATE(167)] = 1680,
  [SMALL_STATE(168)] = 1687,
  [SMALL_STATE(169)] = 1694,
  [SMALL_STATE(170)] = 1698,
  [SMALL_STATE(171)] = 1702,
  [SMALL_STATE(172)] = 1706,
  [SMALL_STATE(173)] = 1710,
  [SMALL_STATE(174)] = 1714,
  [SMALL_STATE(175)] = 1718,
  [SMALL_STATE(176)] = 1722,
  [SMALL_STATE(177)] = 1726,
  [SMALL_STATE(178)] = 1730,
  [SMALL_STATE(179)] = 1734,
  [SMALL_STATE(180)] = 1738,
  [SMALL_STATE(181)] = 1742,
  [SMALL_STATE(182)] = 1746,
  [SMALL_STATE(183)] = 1750,
  [SMALL_STATE(184)] = 1754,
  [SMALL_STATE(185)] = 1758,
  [SMALL_STATE(186)] = 1762,
  [SMALL_STATE(187)] = 1766,
  [SMALL_STATE(188)] = 1770,
  [SMALL_STATE(189)] = 1774,
  [SMALL_STATE(190)] = 1778,
  [SMALL_STATE(191)] = 1782,
  [SMALL_STATE(192)] = 1786,
  [SMALL_STATE(193)] = 1790,
  [SMALL_STATE(194)] = 1794,
  [SMALL_STATE(195)] = 1798,
  [SMALL_STATE(196)] = 1802,
  [SMALL_STATE(197)] = 1806,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(153),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(144),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(158),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(159),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_content, 2, 0, 0), SHIFT_REPEAT(6),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__block_content, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_content, 2, 0, 0), SHIFT_REPEAT(8),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_content, 2, 0, 0), SHIFT_REPEAT(161),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 11),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 15),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 6, 0, 7),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(177),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 6, 0, 5),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 10, 0, 30),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 22),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 10, 0, 29),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 6, 0, 5),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 9),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 21),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 10),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface, 5, 0, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 12),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 5, 0, 3),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 20),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 19),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 5, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 10, 0, 28),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 11, 0, 36),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 5, 0, 2),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 14),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 5, 0, 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 4, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface, 4, 0, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 13),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 5, 0, 17),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 5, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 5, 0, 18),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 4, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 6, 0, 26),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 4, 0, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_type, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_interface_methods_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_interface_methods_repeat1, 2, 0, 0), SHIFT_REPEAT(145),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_parameters, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_methods, 1, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_type, 4, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 5, 0, 16),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_effekts_repeat1, 2, 0, 0), SHIFT_REPEAT(168),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_effekts_repeat1, 2, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effekts, 5, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 6, 0, 35),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 7, 0, 34),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(165),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 2, 0, 8),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(168),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_members_repeat1, 2, 0, 0),
  [292] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_members_repeat1, 2, 0, 0), SHIFT_REPEAT(132),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effekts, 4, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 5, 0, 27),
  [299] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(167),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_parameters_repeat1, 2, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_type, 5, 0, 0),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 6, 0, 25),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 6, 0, 24),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 4),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(167),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_members, 1, 0, 0),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_members, 2, 0, 0),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 4, 0, 0),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 9, 0, 40),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 3, 0, 0),
  [348] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 8, 0, 39),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 8, 0, 38),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 8, 0, 37),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [362] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_member, 4, 0, 6),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [368] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 7, 0, 33),
  [370] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_identifier, 1, 0, 0),
  [372] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 7, 0, 32),
  [374] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 7, 0, 31),
  [376] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_member, 3, 0, 6),
  [378] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 6, 0, 23),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [402] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [428] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [432] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [436] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [438] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [440] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_effekt(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
