#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 138
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define PRODUCTION_ID_COUNT 15

enum ts_symbol_identifiers {
  sym_line_comment = 1,
  anon_sym_record = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LBRACK = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACK = 7,
  anon_sym_COLON = 8,
  anon_sym_type = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_SEMI = 12,
  anon_sym_def = 13,
  anon_sym_EQ = 14,
  anon_sym_SLASH = 15,
  sym_not_implemented = 16,
  anon_sym_val = 17,
  anon_sym_var = 18,
  sym_number = 19,
  aux_sym_generic_identifier_token1 = 20,
  sym_identifier = 21,
  sym_source_file = 22,
  sym__definition = 23,
  sym_record = 24,
  sym_type_parameters = 25,
  sym_parameters = 26,
  sym_parameter = 27,
  sym_parameter_type = 28,
  sym_type = 29,
  sym_type_members = 30,
  sym_type_member = 31,
  sym_function = 32,
  sym_block_parameters = 33,
  sym_return_type = 34,
  sym__expression = 35,
  sym_block = 36,
  aux_sym__block_content = 37,
  sym_statement = 38,
  sym_assignment = 39,
  sym_expression = 40,
  sym_generic_identifier = 41,
  sym_type_identifier = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_type_parameters_repeat1 = 44,
  aux_sym_parameters_repeat1 = 45,
  aux_sym_type_members_repeat1 = 46,
  aux_sym_return_type_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_line_comment] = "line_comment",
  [anon_sym_record] = "record",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_type] = "type",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_def] = "def",
  [anon_sym_EQ] = "=",
  [anon_sym_SLASH] = "/",
  [sym_not_implemented] = "not_implemented",
  [anon_sym_val] = "val",
  [anon_sym_var] = "var",
  [sym_number] = "number",
  [aux_sym_generic_identifier_token1] = "generic_identifier_token1",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_record] = "record",
  [sym_type_parameters] = "type_parameters",
  [sym_parameters] = "parameters",
  [sym_parameter] = "parameter",
  [sym_parameter_type] = "parameter_type",
  [sym_type] = "type",
  [sym_type_members] = "type_members",
  [sym_type_member] = "type_member",
  [sym_function] = "function",
  [sym_block_parameters] = "block_parameters",
  [sym_return_type] = "return_type",
  [sym__expression] = "_expression",
  [sym_block] = "block",
  [aux_sym__block_content] = "_block_content",
  [sym_statement] = "statement",
  [sym_assignment] = "assignment",
  [sym_expression] = "expression",
  [sym_generic_identifier] = "generic_identifier",
  [sym_type_identifier] = "type_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_type_parameters_repeat1] = "type_parameters_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_type_members_repeat1] = "type_members_repeat1",
  [aux_sym_return_type_repeat1] = "return_type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_line_comment] = sym_line_comment,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_not_implemented] = sym_not_implemented,
  [anon_sym_val] = anon_sym_val,
  [anon_sym_var] = anon_sym_var,
  [sym_number] = sym_number,
  [aux_sym_generic_identifier_token1] = aux_sym_generic_identifier_token1,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_record] = sym_record,
  [sym_type_parameters] = sym_type_parameters,
  [sym_parameters] = sym_parameters,
  [sym_parameter] = sym_parameter,
  [sym_parameter_type] = sym_parameter_type,
  [sym_type] = sym_type,
  [sym_type_members] = sym_type_members,
  [sym_type_member] = sym_type_member,
  [sym_function] = sym_function,
  [sym_block_parameters] = sym_block_parameters,
  [sym_return_type] = sym_return_type,
  [sym__expression] = sym__expression,
  [sym_block] = sym_block,
  [aux_sym__block_content] = aux_sym__block_content,
  [sym_statement] = sym_statement,
  [sym_assignment] = sym_assignment,
  [sym_expression] = sym_expression,
  [sym_generic_identifier] = sym_generic_identifier,
  [sym_type_identifier] = sym_type_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_type_parameters_repeat1] = aux_sym_type_parameters_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_type_members_repeat1] = aux_sym_type_members_repeat1,
  [aux_sym_return_type_repeat1] = aux_sym_return_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_not_implemented] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_val] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_generic_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_type_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_members] = {
    .visible = true,
    .named = true,
  },
  [sym_type_member] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_block_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_return_type] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__block_content] = {
    .visible = false,
    .named = false,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_members_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_return_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block_parameters = 1,
  field_body = 2,
  field_kind = 3,
  field_member = 4,
  field_members = 5,
  field_name = 6,
  field_parameters = 7,
  field_return_type = 8,
  field_type_parameters = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block_parameters] = "block_parameters",
  [field_body] = "body",
  [field_kind] = "kind",
  [field_member] = "member",
  [field_members] = "members",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_return_type] = "return_type",
  [field_type_parameters] = "type_parameters",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 3},
  [8] = {.index = 14, .length = 4},
  [9] = {.index = 18, .length = 4},
  [10] = {.index = 22, .length = 4},
  [11] = {.index = 26, .length = 5},
  [12] = {.index = 31, .length = 5},
  [13] = {.index = 36, .length = 5},
  [14] = {.index = 41, .length = 6},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_members, 3},
    {field_name, 1},
  [3] =
    {field_name, 1},
    {field_parameters, 2},
  [5] =
    {field_kind, 2},
    {field_name, 0},
  [7] =
    {field_members, 4},
    {field_name, 1},
    {field_parameters, 2},
  [10] =
    {field_member, 0},
  [11] =
    {field_body, 6},
    {field_name, 1},
    {field_parameters, 3},
  [14] =
    {field_block_parameters, 5},
    {field_body, 7},
    {field_name, 1},
    {field_parameters, 3},
  [18] =
    {field_body, 7},
    {field_name, 1},
    {field_parameters, 4},
    {field_type_parameters, 2},
  [22] =
    {field_body, 8},
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 6},
  [26] =
    {field_block_parameters, 6},
    {field_body, 8},
    {field_name, 1},
    {field_parameters, 4},
    {field_type_parameters, 2},
  [31] =
    {field_block_parameters, 5},
    {field_body, 9},
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 7},
  [36] =
    {field_body, 9},
    {field_name, 1},
    {field_parameters, 4},
    {field_return_type, 7},
    {field_type_parameters, 2},
  [41] =
    {field_block_parameters, 6},
    {field_body, 10},
    {field_name, 1},
    {field_parameters, 4},
    {field_return_type, 8},
    {field_type_parameters, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '(', 20,
        ')', 21,
        ',', 23,
        '/', 33,
        ':', 25,
        ';', 29,
        '<', 3,
        '=', 31,
        '[', 22,
        ']', 24,
        'd', 7,
        'r', 8,
        't', 15,
        'v', 4,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(38);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '(', 20,
        ')', 21,
        ',', 23,
        '/', 32,
        '=', 31,
        '[', 22,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(35);
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 15:
      if (lookahead == 'y') ADVANCE(13);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '/', 2,
        '<', 3,
        'd', 7,
        'r', 8,
        't', 15,
        'v', 4,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_not_implemented);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_val);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_generic_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 16},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 16},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 16},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 16},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 16},
  [29] = {.lex_state = 16},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 16},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 16},
  [37] = {.lex_state = 16},
  [38] = {.lex_state = 16},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 1},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 1},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 1},
  [137] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_not_implemented] = ACTIONS(1),
    [anon_sym_val] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym_generic_identifier_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(133),
    [sym__definition] = STATE(8),
    [sym_record] = STATE(8),
    [sym_type] = STATE(8),
    [sym_function] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [anon_sym_record] = ACTIONS(7),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_def] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(16), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_assignment,
    ACTIONS(18), 2,
      sym_not_implemented,
      sym_number,
    ACTIONS(21), 2,
      anon_sym_val,
      anon_sym_var,
    STATE(2), 4,
      sym__expression,
      sym_block,
      aux_sym__block_content,
      sym_statement,
  [24] = 1,
    ACTIONS(24), 11,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_def,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [38] = 6,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(28), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_assignment,
    ACTIONS(30), 2,
      sym_not_implemented,
      sym_number,
    ACTIONS(32), 2,
      anon_sym_val,
      anon_sym_var,
    STATE(5), 4,
      sym__expression,
      sym_block,
      aux_sym__block_content,
      sym_statement,
  [62] = 6,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(34), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_assignment,
    ACTIONS(32), 2,
      anon_sym_val,
      anon_sym_var,
    ACTIONS(36), 2,
      sym_not_implemented,
      sym_number,
    STATE(2), 4,
      sym__expression,
      sym_block,
      aux_sym__block_content,
      sym_statement,
  [86] = 1,
    ACTIONS(38), 11,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_def,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [100] = 6,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      sym_line_comment,
    ACTIONS(45), 1,
      anon_sym_record,
    ACTIONS(48), 1,
      anon_sym_type,
    ACTIONS(51), 1,
      anon_sym_def,
    STATE(7), 5,
      sym__definition,
      sym_record,
      sym_type,
      sym_function,
      aux_sym_source_file_repeat1,
  [123] = 6,
    ACTIONS(7), 1,
      anon_sym_record,
    ACTIONS(9), 1,
      anon_sym_type,
    ACTIONS(11), 1,
      anon_sym_def,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 1,
      sym_line_comment,
    STATE(7), 5,
      sym__definition,
      sym_record,
      sym_type,
      sym_function,
      aux_sym_source_file_repeat1,
  [146] = 1,
    ACTIONS(58), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_SLASH,
  [157] = 1,
    ACTIONS(60), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [166] = 1,
    ACTIONS(62), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [175] = 1,
    ACTIONS(64), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [184] = 1,
    ACTIONS(66), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [192] = 3,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(68), 2,
      sym_not_implemented,
      sym_number,
    STATE(23), 2,
      sym__expression,
      sym_block,
  [204] = 1,
    ACTIONS(70), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [212] = 5,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(63), 1,
      sym_type_member,
    STATE(114), 1,
      sym_type_identifier,
    STATE(115), 1,
      sym_type_members,
  [228] = 1,
    ACTIONS(76), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [236] = 1,
    ACTIONS(78), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [244] = 1,
    ACTIONS(80), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [252] = 3,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(82), 2,
      sym_not_implemented,
      sym_number,
    STATE(38), 2,
      sym__expression,
      sym_block,
  [264] = 3,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(84), 2,
      sym_not_implemented,
      sym_number,
    STATE(15), 2,
      sym__expression,
      sym_block,
  [276] = 3,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(86), 2,
      sym_not_implemented,
      sym_number,
    STATE(32), 2,
      sym__expression,
      sym_block,
  [288] = 1,
    ACTIONS(88), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [296] = 3,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(90), 2,
      sym_not_implemented,
      sym_number,
    STATE(17), 2,
      sym__expression,
      sym_block,
  [308] = 3,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(92), 2,
      sym_not_implemented,
      sym_number,
    STATE(27), 2,
      sym__expression,
      sym_block,
  [320] = 3,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(94), 2,
      sym_not_implemented,
      sym_number,
    STATE(28), 2,
      sym__expression,
      sym_block,
  [332] = 1,
    ACTIONS(96), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [340] = 1,
    ACTIONS(98), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [348] = 1,
    ACTIONS(100), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [356] = 5,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      sym_type_member,
    STATE(110), 1,
      sym_type_members,
    STATE(114), 1,
      sym_type_identifier,
  [372] = 1,
    ACTIONS(104), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [380] = 1,
    ACTIONS(106), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [388] = 3,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 2,
      sym_not_implemented,
      sym_number,
    STATE(31), 2,
      sym__expression,
      sym_block,
  [400] = 1,
    ACTIONS(110), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [408] = 1,
    ACTIONS(112), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [416] = 1,
    ACTIONS(114), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [424] = 1,
    ACTIONS(116), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [432] = 1,
    ACTIONS(118), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
  [440] = 3,
    ACTIONS(122), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(120), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [451] = 2,
    ACTIONS(126), 1,
      anon_sym_LBRACK,
    ACTIONS(124), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [460] = 4,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    ACTIONS(130), 1,
      sym_identifier,
    STATE(39), 1,
      sym_parameter,
    STATE(121), 1,
      sym_parameters,
  [473] = 4,
    ACTIONS(132), 1,
      anon_sym_COLON,
    ACTIONS(134), 1,
      anon_sym_LBRACE,
    ACTIONS(136), 1,
      anon_sym_EQ,
    STATE(92), 1,
      sym_block_parameters,
  [486] = 4,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_parameter,
    STATE(109), 1,
      sym_parameters,
  [499] = 3,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    ACTIONS(140), 1,
      sym_number,
    STATE(11), 2,
      sym_block,
      sym_expression,
  [510] = 4,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_parameter,
    STATE(118), 1,
      sym_parameters,
  [523] = 3,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(144), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [534] = 3,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(149), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [545] = 4,
    ACTIONS(134), 1,
      anon_sym_LBRACE,
    ACTIONS(153), 1,
      anon_sym_COLON,
    ACTIONS(155), 1,
      anon_sym_EQ,
    STATE(85), 1,
      sym_block_parameters,
  [558] = 3,
    ACTIONS(130), 1,
      sym_identifier,
    STATE(54), 1,
      sym_parameter,
    ACTIONS(149), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [569] = 3,
    ACTIONS(130), 1,
      sym_identifier,
    STATE(54), 1,
      sym_parameter,
    ACTIONS(157), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [580] = 3,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      aux_sym_type_parameters_repeat1,
  [590] = 3,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(103), 1,
      sym_type_member,
    STATE(114), 1,
      sym_type_identifier,
  [600] = 1,
    ACTIONS(163), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [606] = 1,
    ACTIONS(144), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [612] = 3,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(53), 1,
      sym_parameter_type,
  [622] = 3,
    ACTIONS(130), 1,
      sym_identifier,
    STATE(39), 1,
      sym_parameter,
    STATE(112), 1,
      sym_parameters,
  [632] = 3,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      aux_sym_type_parameters_repeat1,
  [642] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_return_type_repeat1,
  [652] = 3,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_RBRACK,
    STATE(62), 1,
      aux_sym_type_parameters_repeat1,
  [662] = 3,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    ACTIONS(178), 1,
      anon_sym_SEMI,
    STATE(60), 1,
      aux_sym_type_members_repeat1,
  [672] = 1,
    ACTIONS(181), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [678] = 3,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      aux_sym_type_parameters_repeat1,
  [688] = 3,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    ACTIONS(187), 1,
      anon_sym_SEMI,
    STATE(66), 1,
      aux_sym_type_members_repeat1,
  [698] = 3,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(69), 1,
      sym_type_identifier,
    STATE(125), 1,
      sym_return_type,
  [708] = 3,
    ACTIONS(130), 1,
      sym_identifier,
    STATE(39), 1,
      sym_parameter,
    STATE(131), 1,
      sym_parameters,
  [718] = 3,
    ACTIONS(187), 1,
      anon_sym_SEMI,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      aux_sym_type_members_repeat1,
  [728] = 3,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_RBRACK,
    STATE(77), 1,
      aux_sym_type_parameters_repeat1,
  [738] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_return_type_repeat1,
  [748] = 3,
    ACTIONS(195), 1,
      anon_sym_LBRACK,
    ACTIONS(197), 1,
      anon_sym_EQ,
    ACTIONS(199), 1,
      anon_sym_SLASH,
  [758] = 1,
    ACTIONS(201), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [764] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_return_type_repeat1,
  [774] = 3,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(69), 1,
      sym_type_identifier,
    STATE(130), 1,
      sym_return_type,
  [784] = 3,
    ACTIONS(130), 1,
      sym_identifier,
    STATE(39), 1,
      sym_parameter,
    STATE(113), 1,
      sym_parameters,
  [794] = 3,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(69), 1,
      sym_type_identifier,
    STATE(127), 1,
      sym_return_type,
  [804] = 3,
    ACTIONS(205), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_return_type_repeat1,
  [814] = 3,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    ACTIONS(210), 1,
      anon_sym_RBRACK,
    STATE(51), 1,
      aux_sym_type_parameters_repeat1,
  [824] = 3,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    ACTIONS(212), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      aux_sym_type_parameters_repeat1,
  [834] = 3,
    ACTIONS(214), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    STATE(123), 1,
      sym_type_parameters,
  [844] = 3,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(218), 1,
      anon_sym_LBRACE,
    STATE(124), 1,
      sym_type_parameters,
  [854] = 3,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    STATE(129), 1,
      sym_type_parameters,
  [864] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      aux_sym_return_type_repeat1,
  [874] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(224), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_return_type_repeat1,
  [884] = 3,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(69), 1,
      sym_type_identifier,
    STATE(111), 1,
      sym_return_type,
  [894] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(224), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      aux_sym_return_type_repeat1,
  [904] = 2,
    ACTIONS(226), 1,
      anon_sym_COLON,
    ACTIONS(228), 1,
      anon_sym_EQ,
  [911] = 2,
    ACTIONS(230), 1,
      aux_sym_generic_identifier_token1,
    STATE(105), 1,
      sym_generic_identifier,
  [918] = 2,
    ACTIONS(230), 1,
      aux_sym_generic_identifier_token1,
    STATE(76), 1,
      sym_generic_identifier,
  [925] = 2,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(79), 1,
      sym_type_identifier,
  [932] = 2,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(84), 1,
      sym_type_identifier,
  [939] = 2,
    ACTIONS(130), 1,
      sym_identifier,
    STATE(54), 1,
      sym_parameter,
  [946] = 2,
    ACTIONS(230), 1,
      aux_sym_generic_identifier_token1,
    STATE(67), 1,
      sym_generic_identifier,
  [953] = 2,
    ACTIONS(232), 1,
      anon_sym_COLON,
    ACTIONS(234), 1,
      anon_sym_EQ,
  [960] = 1,
    ACTIONS(208), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [965] = 1,
    ACTIONS(236), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [970] = 2,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(81), 1,
      sym_type_identifier,
  [977] = 2,
    ACTIONS(230), 1,
      aux_sym_generic_identifier_token1,
    STATE(59), 1,
      sym_generic_identifier,
  [984] = 2,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(93), 1,
      sym_type_identifier,
  [991] = 2,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(80), 1,
      sym_type_identifier,
  [998] = 2,
    ACTIONS(238), 1,
      anon_sym_EQ,
    ACTIONS(240), 1,
      anon_sym_SLASH,
  [1005] = 1,
    ACTIONS(242), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1010] = 2,
    ACTIONS(74), 1,
      aux_sym_generic_identifier_token1,
    STATE(58), 1,
      sym_type_identifier,
  [1017] = 1,
    ACTIONS(244), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1022] = 1,
    ACTIONS(176), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1027] = 1,
    ACTIONS(246), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1032] = 1,
    ACTIONS(168), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1037] = 1,
    ACTIONS(248), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [1042] = 1,
    ACTIONS(250), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1047] = 2,
    ACTIONS(252), 1,
      anon_sym_EQ,
    ACTIONS(254), 1,
      anon_sym_SLASH,
  [1054] = 1,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
  [1058] = 1,
    ACTIONS(258), 1,
      anon_sym_RBRACE,
  [1062] = 1,
    ACTIONS(260), 1,
      anon_sym_EQ,
  [1066] = 1,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
  [1070] = 1,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
  [1074] = 1,
    ACTIONS(266), 1,
      anon_sym_LPAREN,
  [1078] = 1,
    ACTIONS(268), 1,
      anon_sym_RBRACE,
  [1082] = 1,
    ACTIONS(270), 1,
      anon_sym_EQ,
  [1086] = 1,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
  [1090] = 1,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
  [1094] = 1,
    ACTIONS(276), 1,
      anon_sym_LBRACE,
  [1098] = 1,
    ACTIONS(238), 1,
      anon_sym_EQ,
  [1102] = 1,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
  [1106] = 1,
    ACTIONS(280), 1,
      anon_sym_COLON,
  [1110] = 1,
    ACTIONS(282), 1,
      anon_sym_LPAREN,
  [1114] = 1,
    ACTIONS(284), 1,
      anon_sym_LBRACE,
  [1118] = 1,
    ACTIONS(286), 1,
      anon_sym_EQ,
  [1122] = 1,
    ACTIONS(288), 1,
      anon_sym_LBRACE,
  [1126] = 1,
    ACTIONS(290), 1,
      anon_sym_EQ,
  [1130] = 1,
    ACTIONS(292), 1,
      anon_sym_EQ,
  [1134] = 1,
    ACTIONS(294), 1,
      anon_sym_LPAREN,
  [1138] = 1,
    ACTIONS(296), 1,
      anon_sym_EQ,
  [1142] = 1,
    ACTIONS(298), 1,
      anon_sym_RBRACE,
  [1146] = 1,
    ACTIONS(300), 1,
      anon_sym_EQ,
  [1150] = 1,
    ACTIONS(302), 1,
      ts_builtin_sym_end,
  [1154] = 1,
    ACTIONS(304), 1,
      sym_identifier,
  [1158] = 1,
    ACTIONS(306), 1,
      anon_sym_EQ,
  [1162] = 1,
    ACTIONS(308), 1,
      sym_identifier,
  [1166] = 1,
    ACTIONS(310), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 38,
  [SMALL_STATE(5)] = 62,
  [SMALL_STATE(6)] = 86,
  [SMALL_STATE(7)] = 100,
  [SMALL_STATE(8)] = 123,
  [SMALL_STATE(9)] = 146,
  [SMALL_STATE(10)] = 157,
  [SMALL_STATE(11)] = 166,
  [SMALL_STATE(12)] = 175,
  [SMALL_STATE(13)] = 184,
  [SMALL_STATE(14)] = 192,
  [SMALL_STATE(15)] = 204,
  [SMALL_STATE(16)] = 212,
  [SMALL_STATE(17)] = 228,
  [SMALL_STATE(18)] = 236,
  [SMALL_STATE(19)] = 244,
  [SMALL_STATE(20)] = 252,
  [SMALL_STATE(21)] = 264,
  [SMALL_STATE(22)] = 276,
  [SMALL_STATE(23)] = 288,
  [SMALL_STATE(24)] = 296,
  [SMALL_STATE(25)] = 308,
  [SMALL_STATE(26)] = 320,
  [SMALL_STATE(27)] = 332,
  [SMALL_STATE(28)] = 340,
  [SMALL_STATE(29)] = 348,
  [SMALL_STATE(30)] = 356,
  [SMALL_STATE(31)] = 372,
  [SMALL_STATE(32)] = 380,
  [SMALL_STATE(33)] = 388,
  [SMALL_STATE(34)] = 400,
  [SMALL_STATE(35)] = 408,
  [SMALL_STATE(36)] = 416,
  [SMALL_STATE(37)] = 424,
  [SMALL_STATE(38)] = 432,
  [SMALL_STATE(39)] = 440,
  [SMALL_STATE(40)] = 451,
  [SMALL_STATE(41)] = 460,
  [SMALL_STATE(42)] = 473,
  [SMALL_STATE(43)] = 486,
  [SMALL_STATE(44)] = 499,
  [SMALL_STATE(45)] = 510,
  [SMALL_STATE(46)] = 523,
  [SMALL_STATE(47)] = 534,
  [SMALL_STATE(48)] = 545,
  [SMALL_STATE(49)] = 558,
  [SMALL_STATE(50)] = 569,
  [SMALL_STATE(51)] = 580,
  [SMALL_STATE(52)] = 590,
  [SMALL_STATE(53)] = 600,
  [SMALL_STATE(54)] = 606,
  [SMALL_STATE(55)] = 612,
  [SMALL_STATE(56)] = 622,
  [SMALL_STATE(57)] = 632,
  [SMALL_STATE(58)] = 642,
  [SMALL_STATE(59)] = 652,
  [SMALL_STATE(60)] = 662,
  [SMALL_STATE(61)] = 672,
  [SMALL_STATE(62)] = 678,
  [SMALL_STATE(63)] = 688,
  [SMALL_STATE(64)] = 698,
  [SMALL_STATE(65)] = 708,
  [SMALL_STATE(66)] = 718,
  [SMALL_STATE(67)] = 728,
  [SMALL_STATE(68)] = 738,
  [SMALL_STATE(69)] = 748,
  [SMALL_STATE(70)] = 758,
  [SMALL_STATE(71)] = 764,
  [SMALL_STATE(72)] = 774,
  [SMALL_STATE(73)] = 784,
  [SMALL_STATE(74)] = 794,
  [SMALL_STATE(75)] = 804,
  [SMALL_STATE(76)] = 814,
  [SMALL_STATE(77)] = 824,
  [SMALL_STATE(78)] = 834,
  [SMALL_STATE(79)] = 844,
  [SMALL_STATE(80)] = 854,
  [SMALL_STATE(81)] = 864,
  [SMALL_STATE(82)] = 874,
  [SMALL_STATE(83)] = 884,
  [SMALL_STATE(84)] = 894,
  [SMALL_STATE(85)] = 904,
  [SMALL_STATE(86)] = 911,
  [SMALL_STATE(87)] = 918,
  [SMALL_STATE(88)] = 925,
  [SMALL_STATE(89)] = 932,
  [SMALL_STATE(90)] = 939,
  [SMALL_STATE(91)] = 946,
  [SMALL_STATE(92)] = 953,
  [SMALL_STATE(93)] = 960,
  [SMALL_STATE(94)] = 965,
  [SMALL_STATE(95)] = 970,
  [SMALL_STATE(96)] = 977,
  [SMALL_STATE(97)] = 984,
  [SMALL_STATE(98)] = 991,
  [SMALL_STATE(99)] = 998,
  [SMALL_STATE(100)] = 1005,
  [SMALL_STATE(101)] = 1010,
  [SMALL_STATE(102)] = 1017,
  [SMALL_STATE(103)] = 1022,
  [SMALL_STATE(104)] = 1027,
  [SMALL_STATE(105)] = 1032,
  [SMALL_STATE(106)] = 1037,
  [SMALL_STATE(107)] = 1042,
  [SMALL_STATE(108)] = 1047,
  [SMALL_STATE(109)] = 1054,
  [SMALL_STATE(110)] = 1058,
  [SMALL_STATE(111)] = 1062,
  [SMALL_STATE(112)] = 1066,
  [SMALL_STATE(113)] = 1070,
  [SMALL_STATE(114)] = 1074,
  [SMALL_STATE(115)] = 1078,
  [SMALL_STATE(116)] = 1082,
  [SMALL_STATE(117)] = 1086,
  [SMALL_STATE(118)] = 1090,
  [SMALL_STATE(119)] = 1094,
  [SMALL_STATE(120)] = 1098,
  [SMALL_STATE(121)] = 1102,
  [SMALL_STATE(122)] = 1106,
  [SMALL_STATE(123)] = 1110,
  [SMALL_STATE(124)] = 1114,
  [SMALL_STATE(125)] = 1118,
  [SMALL_STATE(126)] = 1122,
  [SMALL_STATE(127)] = 1126,
  [SMALL_STATE(128)] = 1130,
  [SMALL_STATE(129)] = 1134,
  [SMALL_STATE(130)] = 1138,
  [SMALL_STATE(131)] = 1142,
  [SMALL_STATE(132)] = 1146,
  [SMALL_STATE(133)] = 1150,
  [SMALL_STATE(134)] = 1154,
  [SMALL_STATE(135)] = 1158,
  [SMALL_STATE(136)] = 1162,
  [SMALL_STATE(137)] = 1166,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_content, 2, 0, 0), SHIFT_REPEAT(4),
  [16] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__block_content, 2, 0, 0),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_content, 2, 0, 0), SHIFT_REPEAT(2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_content, 2, 0, 0), SHIFT_REPEAT(136),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(134),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 6, 0, 5),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 11, 0, 14),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 7),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 5, 0, 2),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 4, 0, 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 10, 0, 13),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 8),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 10),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 6, 0, 5),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 10, 0, 12),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 9),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 5, 0, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 5, 0, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 5, 0, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 11),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_type, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 4),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_parameters_repeat1, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_members_repeat1, 2, 0, 0),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_members_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_type, 5, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_members, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_members, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_type, 4, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_return_type_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_return_type_repeat1, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_member, 4, 0, 6),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 5, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_member, 3, 0, 6),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_identifier, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 4, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_parameters, 3, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 3, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 4, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 6, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 8, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 9, 0, 0),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 10, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_effekt(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
