#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 200
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define PRODUCTION_ID_COUNT 44

enum ts_symbol_identifiers {
  sym_line_comment = 1,
  anon_sym_record = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LBRACK = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACK = 7,
  anon_sym_COLON = 8,
  anon_sym_type = 9,
  anon_sym_EQ = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_SEMI = 13,
  anon_sym_def = 14,
  anon_sym_SLASH = 15,
  anon_sym_interface = 16,
  sym_not_implemented = 17,
  anon_sym_val = 18,
  anon_sym_var = 19,
  sym_number = 20,
  aux_sym_generic_identifier_token1 = 21,
  sym_source_file = 22,
  sym__definition = 23,
  sym_record = 24,
  sym_type_parameters = 25,
  sym_parameters = 26,
  sym_parameter = 27,
  sym_parameter_type = 28,
  sym_type = 29,
  sym__simple_type = 30,
  sym__complex_type = 31,
  sym_type_members = 32,
  sym_type_member = 33,
  sym_function = 34,
  sym_block_parameters = 35,
  sym_return_type = 36,
  sym_effekts = 37,
  sym_interface = 38,
  sym_interface_methods = 39,
  sym_interface_method = 40,
  sym__expression = 41,
  sym_block = 42,
  aux_sym__block_content = 43,
  sym_statement = 44,
  sym_assignment = 45,
  sym_expression = 46,
  sym_generic_identifier = 47,
  sym_type_identifier = 48,
  sym_identifier = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym_type_parameters_repeat1 = 51,
  aux_sym_parameters_repeat1 = 52,
  aux_sym_type_members_repeat1 = 53,
  aux_sym_effekts_repeat1 = 54,
  aux_sym_interface_methods_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_line_comment] = "line_comment",
  [anon_sym_record] = "record",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_type] = "type",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_def] = "def",
  [anon_sym_SLASH] = "/",
  [anon_sym_interface] = "interface",
  [sym_not_implemented] = "not_implemented",
  [anon_sym_val] = "val",
  [anon_sym_var] = "var",
  [sym_number] = "number",
  [aux_sym_generic_identifier_token1] = "generic_identifier_token1",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_record] = "record",
  [sym_type_parameters] = "type_parameters",
  [sym_parameters] = "parameters",
  [sym_parameter] = "parameter",
  [sym_parameter_type] = "parameter_type",
  [sym_type] = "type",
  [sym__simple_type] = "_simple_type",
  [sym__complex_type] = "_complex_type",
  [sym_type_members] = "type_members",
  [sym_type_member] = "type_member",
  [sym_function] = "function",
  [sym_block_parameters] = "block_parameters",
  [sym_return_type] = "return_type",
  [sym_effekts] = "effekts",
  [sym_interface] = "interface",
  [sym_interface_methods] = "interface_methods",
  [sym_interface_method] = "interface_method",
  [sym__expression] = "_expression",
  [sym_block] = "block",
  [aux_sym__block_content] = "_block_content",
  [sym_statement] = "statement",
  [sym_assignment] = "assignment",
  [sym_expression] = "expression",
  [sym_generic_identifier] = "generic_identifier",
  [sym_type_identifier] = "type_identifier",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_type_parameters_repeat1] = "type_parameters_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_type_members_repeat1] = "type_members_repeat1",
  [aux_sym_effekts_repeat1] = "effekts_repeat1",
  [aux_sym_interface_methods_repeat1] = "interface_methods_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_line_comment] = sym_line_comment,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_interface] = anon_sym_interface,
  [sym_not_implemented] = sym_not_implemented,
  [anon_sym_val] = anon_sym_val,
  [anon_sym_var] = anon_sym_var,
  [sym_number] = sym_number,
  [aux_sym_generic_identifier_token1] = aux_sym_generic_identifier_token1,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_record] = sym_record,
  [sym_type_parameters] = sym_type_parameters,
  [sym_parameters] = sym_parameters,
  [sym_parameter] = sym_parameter,
  [sym_parameter_type] = sym_parameter_type,
  [sym_type] = sym_type,
  [sym__simple_type] = sym__simple_type,
  [sym__complex_type] = sym__complex_type,
  [sym_type_members] = sym_type_members,
  [sym_type_member] = sym_type_member,
  [sym_function] = sym_function,
  [sym_block_parameters] = sym_block_parameters,
  [sym_return_type] = sym_return_type,
  [sym_effekts] = sym_effekts,
  [sym_interface] = sym_interface,
  [sym_interface_methods] = sym_interface_methods,
  [sym_interface_method] = sym_interface_method,
  [sym__expression] = sym__expression,
  [sym_block] = sym_block,
  [aux_sym__block_content] = aux_sym__block_content,
  [sym_statement] = sym_statement,
  [sym_assignment] = sym_assignment,
  [sym_expression] = sym_expression,
  [sym_generic_identifier] = sym_generic_identifier,
  [sym_type_identifier] = sym_type_identifier,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_type_parameters_repeat1] = aux_sym_type_parameters_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_type_members_repeat1] = aux_sym_type_members_repeat1,
  [aux_sym_effekts_repeat1] = aux_sym_effekts_repeat1,
  [aux_sym_interface_methods_repeat1] = aux_sym_interface_methods_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_interface] = {
    .visible = true,
    .named = false,
  },
  [sym_not_implemented] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_val] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_generic_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_type_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_type] = {
    .visible = false,
    .named = true,
  },
  [sym__complex_type] = {
    .visible = false,
    .named = true,
  },
  [sym_type_members] = {
    .visible = true,
    .named = true,
  },
  [sym_type_member] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_block_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_return_type] = {
    .visible = true,
    .named = true,
  },
  [sym_effekts] = {
    .visible = true,
    .named = true,
  },
  [sym_interface] = {
    .visible = true,
    .named = true,
  },
  [sym_interface_methods] = {
    .visible = true,
    .named = true,
  },
  [sym_interface_method] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__block_content] = {
    .visible = false,
    .named = false,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_members_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_effekts_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interface_methods_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block_parameters = 1,
  field_body = 2,
  field_effekts = 3,
  field_kind = 4,
  field_member = 5,
  field_members = 6,
  field_name = 7,
  field_parameters = 8,
  field_return_type = 9,
  field_type_parameters = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block_parameters] = "block_parameters",
  [field_body] = "body",
  [field_effekts] = "effekts",
  [field_kind] = "kind",
  [field_member] = "member",
  [field_members] = "members",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_return_type] = "return_type",
  [field_type_parameters] = "type_parameters",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 3},
  [9] = {.index = 16, .length = 1},
  [10] = {.index = 17, .length = 2},
  [11] = {.index = 19, .length = 1},
  [12] = {.index = 20, .length = 3},
  [13] = {.index = 23, .length = 3},
  [14] = {.index = 26, .length = 3},
  [15] = {.index = 29, .length = 3},
  [16] = {.index = 32, .length = 4},
  [17] = {.index = 36, .length = 4},
  [18] = {.index = 40, .length = 4},
  [19] = {.index = 44, .length = 2},
  [20] = {.index = 46, .length = 2},
  [21] = {.index = 48, .length = 2},
  [22] = {.index = 50, .length = 4},
  [23] = {.index = 54, .length = 4},
  [24] = {.index = 58, .length = 4},
  [25] = {.index = 62, .length = 5},
  [26] = {.index = 67, .length = 2},
  [27] = {.index = 69, .length = 3},
  [28] = {.index = 72, .length = 3},
  [29] = {.index = 75, .length = 3},
  [30] = {.index = 78, .length = 1},
  [31] = {.index = 79, .length = 5},
  [32] = {.index = 84, .length = 5},
  [33] = {.index = 89, .length = 5},
  [34] = {.index = 94, .length = 3},
  [35] = {.index = 97, .length = 3},
  [36] = {.index = 100, .length = 3},
  [37] = {.index = 103, .length = 4},
  [38] = {.index = 107, .length = 1},
  [39] = {.index = 108, .length = 6},
  [40] = {.index = 114, .length = 4},
  [41] = {.index = 118, .length = 4},
  [42] = {.index = 122, .length = 4},
  [43] = {.index = 126, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_members, 2, .inherited = true},
    {field_name, 1},
  [3] =
    {field_name, 1},
    {field_parameters, 2},
  [5] =
    {field_members, 3, .inherited = true},
    {field_name, 1},
    {field_parameters, 2},
  [8] =
    {field_members, 3},
    {field_name, 1},
  [10] =
    {field_members, 1},
  [11] =
    {field_kind, 2},
    {field_name, 0},
  [13] =
    {field_members, 4},
    {field_name, 1},
    {field_parameters, 2},
  [16] =
    {field_member, 0},
  [17] =
    {field_body, 5},
    {field_name, 1},
  [19] =
    {field_effekts, 1},
  [20] =
    {field_block_parameters, 4},
    {field_body, 6},
    {field_name, 1},
  [23] =
    {field_body, 6},
    {field_name, 1},
    {field_parameters, 3},
  [26] =
    {field_body, 6},
    {field_name, 1},
    {field_type_parameters, 2},
  [29] =
    {field_body, 7},
    {field_name, 1},
    {field_return_type, 5},
  [32] =
    {field_block_parameters, 5},
    {field_body, 7},
    {field_name, 1},
    {field_parameters, 3},
  [36] =
    {field_block_parameters, 5},
    {field_body, 7},
    {field_name, 1},
    {field_type_parameters, 2},
  [40] =
    {field_body, 7},
    {field_name, 1},
    {field_parameters, 4},
    {field_type_parameters, 2},
  [44] =
    {field_block_parameters, 4},
    {field_name, 1},
  [46] =
    {field_name, 1},
    {field_parameters, 3},
  [48] =
    {field_name, 1},
    {field_type_parameters, 2},
  [50] =
    {field_block_parameters, 4},
    {field_body, 8},
    {field_name, 1},
    {field_return_type, 6},
  [54] =
    {field_body, 8},
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 6},
  [58] =
    {field_body, 8},
    {field_name, 1},
    {field_return_type, 6},
    {field_type_parameters, 2},
  [62] =
    {field_block_parameters, 6},
    {field_body, 8},
    {field_name, 1},
    {field_parameters, 4},
    {field_type_parameters, 2},
  [67] =
    {field_name, 1},
    {field_return_type, 5},
  [69] =
    {field_block_parameters, 5},
    {field_name, 1},
    {field_parameters, 3},
  [72] =
    {field_block_parameters, 5},
    {field_name, 1},
    {field_type_parameters, 2},
  [75] =
    {field_name, 1},
    {field_parameters, 4},
    {field_type_parameters, 2},
  [78] =
    {field_effekts, 4},
  [79] =
    {field_block_parameters, 5},
    {field_body, 9},
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 7},
  [84] =
    {field_block_parameters, 5},
    {field_body, 9},
    {field_name, 1},
    {field_return_type, 7},
    {field_type_parameters, 2},
  [89] =
    {field_body, 9},
    {field_name, 1},
    {field_parameters, 4},
    {field_return_type, 7},
    {field_type_parameters, 2},
  [94] =
    {field_block_parameters, 4},
    {field_name, 1},
    {field_return_type, 6},
  [97] =
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 6},
  [100] =
    {field_name, 1},
    {field_return_type, 6},
    {field_type_parameters, 2},
  [103] =
    {field_block_parameters, 6},
    {field_name, 1},
    {field_parameters, 4},
    {field_type_parameters, 2},
  [107] =
    {field_effekts, 5},
  [108] =
    {field_block_parameters, 6},
    {field_body, 10},
    {field_name, 1},
    {field_parameters, 4},
    {field_return_type, 8},
    {field_type_parameters, 2},
  [114] =
    {field_block_parameters, 5},
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 7},
  [118] =
    {field_block_parameters, 5},
    {field_name, 1},
    {field_return_type, 7},
    {field_type_parameters, 2},
  [122] =
    {field_name, 1},
    {field_parameters, 4},
    {field_return_type, 7},
    {field_type_parameters, 2},
  [126] =
    {field_block_parameters, 6},
    {field_name, 1},
    {field_parameters, 4},
    {field_return_type, 8},
    {field_type_parameters, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
  [161] = 161,
  [162] = 162,
  [163] = 163,
  [164] = 164,
  [165] = 165,
  [166] = 166,
  [167] = 167,
  [168] = 168,
  [169] = 169,
  [170] = 170,
  [171] = 171,
  [172] = 172,
  [173] = 173,
  [174] = 174,
  [175] = 175,
  [176] = 176,
  [177] = 177,
  [178] = 178,
  [179] = 179,
  [180] = 180,
  [181] = 181,
  [182] = 182,
  [183] = 183,
  [184] = 184,
  [185] = 185,
  [186] = 186,
  [187] = 187,
  [188] = 188,
  [189] = 189,
  [190] = 190,
  [191] = 191,
  [192] = 192,
  [193] = 193,
  [194] = 194,
  [195] = 195,
  [196] = 196,
  [197] = 197,
  [198] = 198,
  [199] = 199,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '(', 29,
        ')', 30,
        ',', 32,
        '/', 42,
        ':', 34,
        ';', 39,
        '<', 4,
        '=', 36,
        '[', 31,
        ']', 33,
        'd', 10,
        'i', 18,
        'r', 11,
        't', 24,
        'v', 5,
        '{', 37,
        '}', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(30);
      if (lookahead == '}') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '=') ADVANCE(36);
      if (lookahead == '[') ADVANCE(31);
      if (lookahead == 'd') ADVANCE(10);
      if (lookahead == '}') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(6);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(45);
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 24:
      if (lookahead == 'y') ADVANCE(20);
      END_STATE();
    case 25:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        ')', 30,
        ',', 32,
        '/', 2,
        '<', 4,
        '[', 31,
        'd', 10,
        'i', 18,
        'r', 11,
        't', 24,
        'v', 5,
        '{', 37,
        '}', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_interface);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_not_implemented);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_val);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_generic_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 25},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 25},
  [4] = {.lex_state = 25},
  [5] = {.lex_state = 25},
  [6] = {.lex_state = 25},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 25},
  [11] = {.lex_state = 25},
  [12] = {.lex_state = 25},
  [13] = {.lex_state = 25},
  [14] = {.lex_state = 25},
  [15] = {.lex_state = 25},
  [16] = {.lex_state = 25},
  [17] = {.lex_state = 25},
  [18] = {.lex_state = 25},
  [19] = {.lex_state = 25},
  [20] = {.lex_state = 25},
  [21] = {.lex_state = 25},
  [22] = {.lex_state = 25},
  [23] = {.lex_state = 25},
  [24] = {.lex_state = 25},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 25},
  [27] = {.lex_state = 25},
  [28] = {.lex_state = 25},
  [29] = {.lex_state = 25},
  [30] = {.lex_state = 25},
  [31] = {.lex_state = 25},
  [32] = {.lex_state = 25},
  [33] = {.lex_state = 25},
  [34] = {.lex_state = 25},
  [35] = {.lex_state = 25},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 25},
  [38] = {.lex_state = 25},
  [39] = {.lex_state = 25},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 25},
  [42] = {.lex_state = 25},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 25},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 25},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 1},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 1},
  [122] = {.lex_state = 1},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 1},
  [125] = {.lex_state = 1},
  [126] = {.lex_state = 1},
  [127] = {.lex_state = 1},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 1},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 1},
  [141] = {.lex_state = 1},
  [142] = {.lex_state = 1},
  [143] = {.lex_state = 1},
  [144] = {.lex_state = 1},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 1},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 1},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 1},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 0},
  [158] = {.lex_state = 1},
  [159] = {.lex_state = 0},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 1},
  [162] = {.lex_state = 0},
  [163] = {.lex_state = 0},
  [164] = {.lex_state = 1},
  [165] = {.lex_state = 0},
  [166] = {.lex_state = 1},
  [167] = {.lex_state = 0},
  [168] = {.lex_state = 1},
  [169] = {.lex_state = 0},
  [170] = {.lex_state = 0},
  [171] = {.lex_state = 1},
  [172] = {.lex_state = 1},
  [173] = {.lex_state = 0},
  [174] = {.lex_state = 0},
  [175] = {.lex_state = 0},
  [176] = {.lex_state = 0},
  [177] = {.lex_state = 0},
  [178] = {.lex_state = 0},
  [179] = {.lex_state = 0},
  [180] = {.lex_state = 0},
  [181] = {.lex_state = 0},
  [182] = {.lex_state = 0},
  [183] = {.lex_state = 0},
  [184] = {.lex_state = 0},
  [185] = {.lex_state = 0},
  [186] = {.lex_state = 0},
  [187] = {.lex_state = 0},
  [188] = {.lex_state = 0},
  [189] = {.lex_state = 0},
  [190] = {.lex_state = 0},
  [191] = {.lex_state = 0},
  [192] = {.lex_state = 0},
  [193] = {.lex_state = 0},
  [194] = {.lex_state = 0},
  [195] = {.lex_state = 0},
  [196] = {.lex_state = 0},
  [197] = {.lex_state = 0},
  [198] = {.lex_state = 0},
  [199] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_interface] = ACTIONS(1),
    [sym_not_implemented] = ACTIONS(1),
    [anon_sym_val] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(180),
    [sym__definition] = STATE(4),
    [sym_record] = STATE(4),
    [sym_type] = STATE(4),
    [sym_function] = STATE(4),
    [sym_interface] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [anon_sym_record] = ACTIONS(7),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_def] = ACTIONS(11),
    [anon_sym_interface] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(17), 1,
      anon_sym_SLASH,
    ACTIONS(15), 13,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_interface,
  [19] = 1,
    ACTIONS(19), 12,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_interface,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [34] = 7,
    ACTIONS(7), 1,
      anon_sym_record,
    ACTIONS(9), 1,
      anon_sym_type,
    ACTIONS(11), 1,
      anon_sym_def,
    ACTIONS(13), 1,
      anon_sym_interface,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_line_comment,
    STATE(6), 6,
      sym__definition,
      sym_record,
      sym_type,
      sym_function,
      sym_interface,
      aux_sym_source_file_repeat1,
  [61] = 1,
    ACTIONS(25), 12,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_interface,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [76] = 7,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_line_comment,
    ACTIONS(32), 1,
      anon_sym_record,
    ACTIONS(35), 1,
      anon_sym_type,
    ACTIONS(38), 1,
      anon_sym_def,
    ACTIONS(41), 1,
      anon_sym_interface,
    STATE(6), 6,
      sym__definition,
      sym_record,
      sym_type,
      sym_function,
      sym_interface,
      aux_sym_source_file_repeat1,
  [103] = 6,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      sym_assignment,
    ACTIONS(48), 2,
      sym_not_implemented,
      sym_number,
    ACTIONS(50), 2,
      anon_sym_val,
      anon_sym_var,
    STATE(8), 4,
      sym__expression,
      sym_block,
      aux_sym__block_content,
      sym_statement,
  [127] = 6,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      sym_assignment,
    ACTIONS(50), 2,
      anon_sym_val,
      anon_sym_var,
    ACTIONS(54), 2,
      sym_not_implemented,
      sym_number,
    STATE(9), 4,
      sym__expression,
      sym_block,
      aux_sym__block_content,
      sym_statement,
  [151] = 6,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      sym_assignment,
    ACTIONS(61), 2,
      sym_not_implemented,
      sym_number,
    ACTIONS(64), 2,
      anon_sym_val,
      anon_sym_var,
    STATE(9), 4,
      sym__expression,
      sym_block,
      aux_sym__block_content,
      sym_statement,
  [175] = 2,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 9,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_interface,
  [190] = 1,
    ACTIONS(71), 9,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_interface,
  [202] = 1,
    ACTIONS(73), 9,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_RBRACE,
      anon_sym_def,
      anon_sym_interface,
  [214] = 1,
    ACTIONS(75), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [223] = 1,
    ACTIONS(77), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [232] = 1,
    ACTIONS(79), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [241] = 1,
    ACTIONS(81), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [250] = 1,
    ACTIONS(83), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [259] = 1,
    ACTIONS(85), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [268] = 1,
    ACTIONS(87), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [277] = 1,
    ACTIONS(89), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [286] = 1,
    ACTIONS(91), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [295] = 1,
    ACTIONS(93), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [304] = 1,
    ACTIONS(95), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [313] = 1,
    ACTIONS(97), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [322] = 1,
    ACTIONS(99), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [331] = 1,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [340] = 1,
    ACTIONS(103), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [349] = 1,
    ACTIONS(105), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [358] = 1,
    ACTIONS(107), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [367] = 1,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [376] = 1,
    ACTIONS(111), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [385] = 1,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [394] = 1,
    ACTIONS(115), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [403] = 1,
    ACTIONS(117), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [412] = 1,
    ACTIONS(119), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [421] = 1,
    ACTIONS(121), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [430] = 1,
    ACTIONS(123), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [439] = 1,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [448] = 1,
    ACTIONS(127), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [457] = 4,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(133), 1,
      anon_sym_SLASH,
    STATE(109), 1,
      sym_effekts,
    ACTIONS(131), 3,
      anon_sym_EQ,
      anon_sym_RBRACE,
      anon_sym_def,
  [472] = 1,
    ACTIONS(135), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [481] = 1,
    ACTIONS(137), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [490] = 6,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    ACTIONS(141), 1,
      anon_sym_EQ,
    ACTIONS(143), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym__simple_type,
    STATE(23), 1,
      sym__complex_type,
    STATE(86), 1,
      sym_type_parameters,
  [509] = 1,
    ACTIONS(145), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [518] = 1,
    ACTIONS(147), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_not_implemented,
      anon_sym_val,
      anon_sym_var,
      sym_number,
  [527] = 1,
    ACTIONS(149), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_record,
      anon_sym_type,
      anon_sym_def,
      anon_sym_interface,
  [536] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(151), 2,
      sym_not_implemented,
      sym_number,
    STATE(28), 2,
      sym__expression,
      sym_block,
  [548] = 4,
    ACTIONS(153), 1,
      anon_sym_COLON,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    STATE(119), 1,
      sym_block_parameters,
    ACTIONS(157), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [562] = 4,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    STATE(104), 1,
      sym_parameter,
    STATE(173), 1,
      sym_identifier,
    ACTIONS(159), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [576] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(163), 2,
      sym_not_implemented,
      sym_number,
    STATE(29), 2,
      sym__expression,
      sym_block,
  [588] = 3,
    ACTIONS(133), 1,
      anon_sym_SLASH,
    STATE(113), 1,
      sym_effekts,
    ACTIONS(165), 3,
      anon_sym_EQ,
      anon_sym_RBRACE,
      anon_sym_def,
  [600] = 5,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_parameter,
    STATE(173), 1,
      sym_identifier,
    STATE(175), 1,
      sym_parameters,
  [616] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(169), 2,
      sym_not_implemented,
      sym_number,
    STATE(21), 2,
      sym__expression,
      sym_block,
  [628] = 5,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_parameter,
    STATE(173), 1,
      sym_identifier,
    STATE(195), 1,
      sym_parameters,
  [644] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(173), 2,
      sym_not_implemented,
      sym_number,
    STATE(17), 2,
      sym__expression,
      sym_block,
  [656] = 4,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(175), 1,
      anon_sym_COLON,
    STATE(139), 1,
      sym_block_parameters,
    ACTIONS(177), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [670] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(179), 2,
      sym_not_implemented,
      sym_number,
    STATE(37), 2,
      sym__expression,
      sym_block,
  [682] = 5,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_parameter,
    STATE(173), 1,
      sym_identifier,
    STATE(186), 1,
      sym_parameters,
  [698] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(183), 2,
      sym_not_implemented,
      sym_number,
    STATE(38), 2,
      sym__expression,
      sym_block,
  [710] = 4,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_COLON,
    STATE(117), 1,
      sym_block_parameters,
    ACTIONS(187), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [724] = 5,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_parameter,
    STATE(173), 1,
      sym_identifier,
    STATE(192), 1,
      sym_parameters,
  [740] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(191), 2,
      sym_not_implemented,
      sym_number,
    STATE(42), 2,
      sym__expression,
      sym_block,
  [752] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(193), 2,
      sym_not_implemented,
      sym_number,
    STATE(16), 2,
      sym__expression,
      sym_block,
  [764] = 4,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(195), 1,
      anon_sym_COLON,
    STATE(114), 1,
      sym_block_parameters,
    ACTIONS(197), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [778] = 3,
    ACTIONS(133), 1,
      anon_sym_SLASH,
    STATE(111), 1,
      sym_effekts,
    ACTIONS(199), 3,
      anon_sym_EQ,
      anon_sym_RBRACE,
      anon_sym_def,
  [790] = 4,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
    ACTIONS(203), 1,
      anon_sym_def,
    STATE(194), 1,
      sym_interface_methods,
    STATE(83), 2,
      sym_interface_method,
      aux_sym_interface_methods_repeat1,
  [804] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(205), 2,
      sym_not_implemented,
      sym_number,
    STATE(24), 2,
      sym__expression,
      sym_block,
  [816] = 5,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_parameter,
    STATE(173), 1,
      sym_identifier,
    STATE(198), 1,
      sym_parameters,
  [832] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(209), 2,
      sym_not_implemented,
      sym_number,
    STATE(41), 2,
      sym__expression,
      sym_block,
  [844] = 5,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(100), 1,
      sym_type_member,
    STATE(178), 1,
      sym_type_identifier,
    STATE(197), 1,
      sym_type_members,
  [860] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(215), 2,
      sym_not_implemented,
      sym_number,
    STATE(20), 2,
      sym__expression,
      sym_block,
  [872] = 5,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_parameter,
    STATE(173), 1,
      sym_identifier,
    STATE(185), 1,
      sym_parameters,
  [888] = 4,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    STATE(104), 1,
      sym_parameter,
    STATE(173), 1,
      sym_identifier,
    ACTIONS(219), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [902] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(221), 2,
      sym_not_implemented,
      sym_number,
    STATE(30), 2,
      sym__expression,
      sym_block,
  [914] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(223), 2,
      sym_not_implemented,
      sym_number,
    STATE(18), 2,
      sym__expression,
      sym_block,
  [926] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(225), 2,
      sym_not_implemented,
      sym_number,
    STATE(31), 2,
      sym__expression,
      sym_block,
  [938] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(227), 2,
      sym_not_implemented,
      sym_number,
    STATE(14), 2,
      sym__expression,
      sym_block,
  [950] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(229), 2,
      sym_not_implemented,
      sym_number,
    STATE(26), 2,
      sym__expression,
      sym_block,
  [962] = 5,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    ACTIONS(231), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_parameter,
    STATE(173), 1,
      sym_identifier,
    STATE(188), 1,
      sym_parameters,
  [978] = 3,
    ACTIONS(233), 1,
      anon_sym_COMMA,
    STATE(91), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(159), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [989] = 4,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(235), 1,
      anon_sym_COLON,
    ACTIONS(237), 1,
      anon_sym_EQ,
    STATE(167), 1,
      sym_block_parameters,
  [1002] = 4,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(239), 1,
      anon_sym_COLON,
    ACTIONS(241), 1,
      anon_sym_EQ,
    STATE(169), 1,
      sym_block_parameters,
  [1015] = 3,
    ACTIONS(203), 1,
      anon_sym_def,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
    STATE(93), 2,
      sym_interface_method,
      aux_sym_interface_methods_repeat1,
  [1026] = 3,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(245), 1,
      sym_number,
    STATE(36), 2,
      sym_block,
      sym_expression,
  [1037] = 3,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(247), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1048] = 4,
    ACTIONS(141), 1,
      anon_sym_EQ,
    ACTIONS(143), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      sym__complex_type,
    STATE(39), 1,
      sym__simple_type,
  [1061] = 4,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    STATE(85), 1,
      sym_parameter,
    STATE(173), 1,
      sym_identifier,
    STATE(189), 1,
      sym_parameters,
  [1074] = 4,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(251), 1,
      anon_sym_COLON,
    ACTIONS(253), 1,
      anon_sym_EQ,
    STATE(157), 1,
      sym_block_parameters,
  [1087] = 1,
    ACTIONS(255), 4,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_RBRACE,
      anon_sym_def,
  [1094] = 4,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(257), 1,
      anon_sym_COLON,
    ACTIONS(259), 1,
      anon_sym_EQ,
    STATE(159), 1,
      sym_block_parameters,
  [1107] = 3,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    STATE(91), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(261), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1118] = 1,
    ACTIONS(266), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_COLON,
      anon_sym_EQ,
  [1125] = 3,
    ACTIONS(268), 1,
      anon_sym_RBRACE,
    ACTIONS(270), 1,
      anon_sym_def,
    STATE(93), 2,
      sym_interface_method,
      aux_sym_interface_methods_repeat1,
  [1136] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(182), 1,
      sym_return_type,
  [1146] = 3,
    ACTIONS(273), 1,
      anon_sym_RBRACE,
    ACTIONS(275), 1,
      anon_sym_SEMI,
    STATE(95), 1,
      aux_sym_type_members_repeat1,
  [1156] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(147), 1,
      sym_return_type,
  [1166] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(174), 1,
      sym_return_type,
  [1176] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(181), 1,
      sym_return_type,
  [1186] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(150), 1,
      sym_return_type,
  [1196] = 3,
    ACTIONS(278), 1,
      anon_sym_RBRACE,
    ACTIONS(280), 1,
      anon_sym_SEMI,
    STATE(123), 1,
      aux_sym_type_members_repeat1,
  [1206] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(151), 1,
      sym_return_type,
  [1216] = 3,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    ACTIONS(282), 1,
      anon_sym_LPAREN,
    STATE(183), 1,
      sym_type_parameters,
  [1226] = 3,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    STATE(104), 1,
      sym_parameter,
    STATE(173), 1,
      sym_identifier,
  [1236] = 1,
    ACTIONS(261), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1242] = 3,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(286), 1,
      anon_sym_RBRACK,
    STATE(133), 1,
      aux_sym_type_parameters_repeat1,
  [1252] = 3,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    ACTIONS(288), 1,
      anon_sym_LPAREN,
    STATE(187), 1,
      sym_type_parameters,
  [1262] = 3,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
    STATE(128), 1,
      aux_sym_effekts_repeat1,
  [1272] = 1,
    ACTIONS(294), 3,
      anon_sym_EQ,
      anon_sym_RBRACE,
      anon_sym_def,
  [1278] = 1,
    ACTIONS(296), 3,
      anon_sym_EQ,
      anon_sym_RBRACE,
      anon_sym_def,
  [1284] = 3,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    ACTIONS(298), 1,
      anon_sym_LPAREN,
    STATE(179), 1,
      sym_type_parameters,
  [1294] = 1,
    ACTIONS(300), 3,
      anon_sym_EQ,
      anon_sym_RBRACE,
      anon_sym_def,
  [1300] = 1,
    ACTIONS(302), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1306] = 1,
    ACTIONS(304), 3,
      anon_sym_EQ,
      anon_sym_RBRACE,
      anon_sym_def,
  [1312] = 2,
    ACTIONS(306), 1,
      anon_sym_COLON,
    ACTIONS(308), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1320] = 1,
    ACTIONS(310), 3,
      anon_sym_EQ,
      anon_sym_RBRACE,
      anon_sym_def,
  [1326] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(160), 1,
      sym_return_type,
  [1336] = 2,
    ACTIONS(312), 1,
      anon_sym_COLON,
    ACTIONS(314), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1344] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(196), 1,
      sym_return_type,
  [1354] = 2,
    ACTIONS(316), 1,
      anon_sym_COLON,
    ACTIONS(318), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1362] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(162), 1,
      sym_return_type,
  [1372] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(190), 1,
      sym_return_type,
  [1382] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(199), 1,
      sym_return_type,
  [1392] = 3,
    ACTIONS(280), 1,
      anon_sym_SEMI,
    ACTIONS(320), 1,
      anon_sym_RBRACE,
    STATE(95), 1,
      aux_sym_type_members_repeat1,
  [1402] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(191), 1,
      sym_return_type,
  [1412] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(146), 1,
      sym_type_member,
    STATE(178), 1,
      sym_type_identifier,
  [1422] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(163), 1,
      sym_return_type,
  [1432] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(10), 1,
      sym_type_identifier,
    STATE(34), 1,
      sym_parameter_type,
  [1442] = 3,
    ACTIONS(322), 1,
      anon_sym_COMMA,
    ACTIONS(325), 1,
      anon_sym_RBRACE,
    STATE(128), 1,
      aux_sym_effekts_repeat1,
  [1452] = 3,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(327), 1,
      anon_sym_RBRACK,
    STATE(105), 1,
      aux_sym_type_parameters_repeat1,
  [1462] = 3,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(329), 1,
      anon_sym_RBRACK,
    STATE(133), 1,
      aux_sym_type_parameters_repeat1,
  [1472] = 1,
    ACTIONS(331), 3,
      anon_sym_LPAREN,
      anon_sym_EQ,
      anon_sym_LBRACE,
  [1478] = 3,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(333), 1,
      anon_sym_RBRACK,
    STATE(135), 1,
      aux_sym_type_parameters_repeat1,
  [1488] = 3,
    ACTIONS(335), 1,
      anon_sym_COMMA,
    ACTIONS(338), 1,
      anon_sym_RBRACK,
    STATE(133), 1,
      aux_sym_type_parameters_repeat1,
  [1498] = 3,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(340), 1,
      anon_sym_RBRACE,
    STATE(107), 1,
      aux_sym_effekts_repeat1,
  [1508] = 3,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(342), 1,
      anon_sym_RBRACK,
    STATE(133), 1,
      aux_sym_type_parameters_repeat1,
  [1518] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(10), 1,
      sym_type_identifier,
    STATE(112), 1,
      sym_parameter_type,
  [1528] = 1,
    ACTIONS(344), 3,
      anon_sym_LPAREN,
      anon_sym_EQ,
      anon_sym_LBRACE,
  [1534] = 3,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(346), 1,
      anon_sym_RBRACK,
    STATE(130), 1,
      aux_sym_type_parameters_repeat1,
  [1544] = 2,
    ACTIONS(348), 1,
      anon_sym_COLON,
    ACTIONS(350), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1552] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(165), 1,
      sym_return_type,
  [1562] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(145), 1,
      sym_return_type,
  [1572] = 3,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(40), 1,
      sym_type_identifier,
    STATE(184), 1,
      sym_return_type,
  [1582] = 2,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    STATE(193), 1,
      sym_identifier,
  [1589] = 2,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(134), 1,
      sym_type_identifier,
  [1596] = 1,
    ACTIONS(352), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1601] = 1,
    ACTIONS(273), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1606] = 1,
    ACTIONS(354), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1611] = 1,
    ACTIONS(338), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1616] = 2,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    STATE(110), 1,
      sym_identifier,
  [1623] = 1,
    ACTIONS(356), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1628] = 1,
    ACTIONS(358), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1633] = 2,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(43), 1,
      sym_type_identifier,
  [1640] = 1,
    ACTIONS(360), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1645] = 1,
    ACTIONS(362), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1650] = 2,
    ACTIONS(364), 1,
      aux_sym_generic_identifier_token1,
    STATE(148), 1,
      sym_generic_identifier,
  [1657] = 1,
    ACTIONS(325), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1662] = 2,
    ACTIONS(366), 1,
      anon_sym_COLON,
    ACTIONS(368), 1,
      anon_sym_EQ,
  [1669] = 2,
    ACTIONS(364), 1,
      aux_sym_generic_identifier_token1,
    STATE(132), 1,
      sym_generic_identifier,
  [1676] = 2,
    ACTIONS(370), 1,
      anon_sym_COLON,
    ACTIONS(372), 1,
      anon_sym_EQ,
  [1683] = 1,
    ACTIONS(374), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1688] = 2,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(102), 1,
      sym_type_identifier,
  [1695] = 1,
    ACTIONS(376), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1700] = 1,
    ACTIONS(378), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1705] = 2,
    ACTIONS(161), 1,
      aux_sym_generic_identifier_token1,
    STATE(106), 1,
      sym_identifier,
  [1712] = 1,
    ACTIONS(380), 2,
      anon_sym_RBRACE,
      anon_sym_def,
  [1717] = 2,
    ACTIONS(364), 1,
      aux_sym_generic_identifier_token1,
    STATE(129), 1,
      sym_generic_identifier,
  [1724] = 2,
    ACTIONS(382), 1,
      anon_sym_COLON,
    ACTIONS(384), 1,
      anon_sym_EQ,
  [1731] = 2,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(177), 1,
      sym_type_identifier,
  [1738] = 2,
    ACTIONS(386), 1,
      anon_sym_COLON,
    ACTIONS(388), 1,
      anon_sym_EQ,
  [1745] = 1,
    ACTIONS(390), 2,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1750] = 2,
    ACTIONS(364), 1,
      aux_sym_generic_identifier_token1,
    STATE(138), 1,
      sym_generic_identifier,
  [1757] = 2,
    ACTIONS(213), 1,
      aux_sym_generic_identifier_token1,
    STATE(156), 1,
      sym_type_identifier,
  [1764] = 1,
    ACTIONS(392), 1,
      anon_sym_COLON,
  [1768] = 1,
    ACTIONS(394), 1,
      anon_sym_EQ,
  [1772] = 1,
    ACTIONS(396), 1,
      anon_sym_RPAREN,
  [1776] = 1,
    ACTIONS(398), 1,
      anon_sym_LBRACE,
  [1780] = 1,
    ACTIONS(400), 1,
      anon_sym_LBRACE,
  [1784] = 1,
    ACTIONS(402), 1,
      anon_sym_LPAREN,
  [1788] = 1,
    ACTIONS(404), 1,
      anon_sym_LPAREN,
  [1792] = 1,
    ACTIONS(406), 1,
      ts_builtin_sym_end,
  [1796] = 1,
    ACTIONS(408), 1,
      anon_sym_EQ,
  [1800] = 1,
    ACTIONS(410), 1,
      anon_sym_EQ,
  [1804] = 1,
    ACTIONS(412), 1,
      anon_sym_LPAREN,
  [1808] = 1,
    ACTIONS(414), 1,
      anon_sym_EQ,
  [1812] = 1,
    ACTIONS(416), 1,
      anon_sym_RPAREN,
  [1816] = 1,
    ACTIONS(418), 1,
      anon_sym_RPAREN,
  [1820] = 1,
    ACTIONS(420), 1,
      anon_sym_LPAREN,
  [1824] = 1,
    ACTIONS(422), 1,
      anon_sym_RPAREN,
  [1828] = 1,
    ACTIONS(424), 1,
      anon_sym_RBRACE,
  [1832] = 1,
    ACTIONS(426), 1,
      anon_sym_EQ,
  [1836] = 1,
    ACTIONS(428), 1,
      anon_sym_EQ,
  [1840] = 1,
    ACTIONS(430), 1,
      anon_sym_RPAREN,
  [1844] = 1,
    ACTIONS(432), 1,
      anon_sym_EQ,
  [1848] = 1,
    ACTIONS(434), 1,
      anon_sym_RBRACE,
  [1852] = 1,
    ACTIONS(436), 1,
      anon_sym_RPAREN,
  [1856] = 1,
    ACTIONS(438), 1,
      anon_sym_EQ,
  [1860] = 1,
    ACTIONS(440), 1,
      anon_sym_RBRACE,
  [1864] = 1,
    ACTIONS(442), 1,
      anon_sym_RPAREN,
  [1868] = 1,
    ACTIONS(444), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 19,
  [SMALL_STATE(4)] = 34,
  [SMALL_STATE(5)] = 61,
  [SMALL_STATE(6)] = 76,
  [SMALL_STATE(7)] = 103,
  [SMALL_STATE(8)] = 127,
  [SMALL_STATE(9)] = 151,
  [SMALL_STATE(10)] = 175,
  [SMALL_STATE(11)] = 190,
  [SMALL_STATE(12)] = 202,
  [SMALL_STATE(13)] = 214,
  [SMALL_STATE(14)] = 223,
  [SMALL_STATE(15)] = 232,
  [SMALL_STATE(16)] = 241,
  [SMALL_STATE(17)] = 250,
  [SMALL_STATE(18)] = 259,
  [SMALL_STATE(19)] = 268,
  [SMALL_STATE(20)] = 277,
  [SMALL_STATE(21)] = 286,
  [SMALL_STATE(22)] = 295,
  [SMALL_STATE(23)] = 304,
  [SMALL_STATE(24)] = 313,
  [SMALL_STATE(25)] = 322,
  [SMALL_STATE(26)] = 331,
  [SMALL_STATE(27)] = 340,
  [SMALL_STATE(28)] = 349,
  [SMALL_STATE(29)] = 358,
  [SMALL_STATE(30)] = 367,
  [SMALL_STATE(31)] = 376,
  [SMALL_STATE(32)] = 385,
  [SMALL_STATE(33)] = 394,
  [SMALL_STATE(34)] = 403,
  [SMALL_STATE(35)] = 412,
  [SMALL_STATE(36)] = 421,
  [SMALL_STATE(37)] = 430,
  [SMALL_STATE(38)] = 439,
  [SMALL_STATE(39)] = 448,
  [SMALL_STATE(40)] = 457,
  [SMALL_STATE(41)] = 472,
  [SMALL_STATE(42)] = 481,
  [SMALL_STATE(43)] = 490,
  [SMALL_STATE(44)] = 509,
  [SMALL_STATE(45)] = 518,
  [SMALL_STATE(46)] = 527,
  [SMALL_STATE(47)] = 536,
  [SMALL_STATE(48)] = 548,
  [SMALL_STATE(49)] = 562,
  [SMALL_STATE(50)] = 576,
  [SMALL_STATE(51)] = 588,
  [SMALL_STATE(52)] = 600,
  [SMALL_STATE(53)] = 616,
  [SMALL_STATE(54)] = 628,
  [SMALL_STATE(55)] = 644,
  [SMALL_STATE(56)] = 656,
  [SMALL_STATE(57)] = 670,
  [SMALL_STATE(58)] = 682,
  [SMALL_STATE(59)] = 698,
  [SMALL_STATE(60)] = 710,
  [SMALL_STATE(61)] = 724,
  [SMALL_STATE(62)] = 740,
  [SMALL_STATE(63)] = 752,
  [SMALL_STATE(64)] = 764,
  [SMALL_STATE(65)] = 778,
  [SMALL_STATE(66)] = 790,
  [SMALL_STATE(67)] = 804,
  [SMALL_STATE(68)] = 816,
  [SMALL_STATE(69)] = 832,
  [SMALL_STATE(70)] = 844,
  [SMALL_STATE(71)] = 860,
  [SMALL_STATE(72)] = 872,
  [SMALL_STATE(73)] = 888,
  [SMALL_STATE(74)] = 902,
  [SMALL_STATE(75)] = 914,
  [SMALL_STATE(76)] = 926,
  [SMALL_STATE(77)] = 938,
  [SMALL_STATE(78)] = 950,
  [SMALL_STATE(79)] = 962,
  [SMALL_STATE(80)] = 978,
  [SMALL_STATE(81)] = 989,
  [SMALL_STATE(82)] = 1002,
  [SMALL_STATE(83)] = 1015,
  [SMALL_STATE(84)] = 1026,
  [SMALL_STATE(85)] = 1037,
  [SMALL_STATE(86)] = 1048,
  [SMALL_STATE(87)] = 1061,
  [SMALL_STATE(88)] = 1074,
  [SMALL_STATE(89)] = 1087,
  [SMALL_STATE(90)] = 1094,
  [SMALL_STATE(91)] = 1107,
  [SMALL_STATE(92)] = 1118,
  [SMALL_STATE(93)] = 1125,
  [SMALL_STATE(94)] = 1136,
  [SMALL_STATE(95)] = 1146,
  [SMALL_STATE(96)] = 1156,
  [SMALL_STATE(97)] = 1166,
  [SMALL_STATE(98)] = 1176,
  [SMALL_STATE(99)] = 1186,
  [SMALL_STATE(100)] = 1196,
  [SMALL_STATE(101)] = 1206,
  [SMALL_STATE(102)] = 1216,
  [SMALL_STATE(103)] = 1226,
  [SMALL_STATE(104)] = 1236,
  [SMALL_STATE(105)] = 1242,
  [SMALL_STATE(106)] = 1252,
  [SMALL_STATE(107)] = 1262,
  [SMALL_STATE(108)] = 1272,
  [SMALL_STATE(109)] = 1278,
  [SMALL_STATE(110)] = 1284,
  [SMALL_STATE(111)] = 1294,
  [SMALL_STATE(112)] = 1300,
  [SMALL_STATE(113)] = 1306,
  [SMALL_STATE(114)] = 1312,
  [SMALL_STATE(115)] = 1320,
  [SMALL_STATE(116)] = 1326,
  [SMALL_STATE(117)] = 1336,
  [SMALL_STATE(118)] = 1344,
  [SMALL_STATE(119)] = 1354,
  [SMALL_STATE(120)] = 1362,
  [SMALL_STATE(121)] = 1372,
  [SMALL_STATE(122)] = 1382,
  [SMALL_STATE(123)] = 1392,
  [SMALL_STATE(124)] = 1402,
  [SMALL_STATE(125)] = 1412,
  [SMALL_STATE(126)] = 1422,
  [SMALL_STATE(127)] = 1432,
  [SMALL_STATE(128)] = 1442,
  [SMALL_STATE(129)] = 1452,
  [SMALL_STATE(130)] = 1462,
  [SMALL_STATE(131)] = 1472,
  [SMALL_STATE(132)] = 1478,
  [SMALL_STATE(133)] = 1488,
  [SMALL_STATE(134)] = 1498,
  [SMALL_STATE(135)] = 1508,
  [SMALL_STATE(136)] = 1518,
  [SMALL_STATE(137)] = 1528,
  [SMALL_STATE(138)] = 1534,
  [SMALL_STATE(139)] = 1544,
  [SMALL_STATE(140)] = 1552,
  [SMALL_STATE(141)] = 1562,
  [SMALL_STATE(142)] = 1572,
  [SMALL_STATE(143)] = 1582,
  [SMALL_STATE(144)] = 1589,
  [SMALL_STATE(145)] = 1596,
  [SMALL_STATE(146)] = 1601,
  [SMALL_STATE(147)] = 1606,
  [SMALL_STATE(148)] = 1611,
  [SMALL_STATE(149)] = 1616,
  [SMALL_STATE(150)] = 1623,
  [SMALL_STATE(151)] = 1628,
  [SMALL_STATE(152)] = 1633,
  [SMALL_STATE(153)] = 1640,
  [SMALL_STATE(154)] = 1645,
  [SMALL_STATE(155)] = 1650,
  [SMALL_STATE(156)] = 1657,
  [SMALL_STATE(157)] = 1662,
  [SMALL_STATE(158)] = 1669,
  [SMALL_STATE(159)] = 1676,
  [SMALL_STATE(160)] = 1683,
  [SMALL_STATE(161)] = 1688,
  [SMALL_STATE(162)] = 1695,
  [SMALL_STATE(163)] = 1700,
  [SMALL_STATE(164)] = 1705,
  [SMALL_STATE(165)] = 1712,
  [SMALL_STATE(166)] = 1717,
  [SMALL_STATE(167)] = 1724,
  [SMALL_STATE(168)] = 1731,
  [SMALL_STATE(169)] = 1738,
  [SMALL_STATE(170)] = 1745,
  [SMALL_STATE(171)] = 1750,
  [SMALL_STATE(172)] = 1757,
  [SMALL_STATE(173)] = 1764,
  [SMALL_STATE(174)] = 1768,
  [SMALL_STATE(175)] = 1772,
  [SMALL_STATE(176)] = 1776,
  [SMALL_STATE(177)] = 1780,
  [SMALL_STATE(178)] = 1784,
  [SMALL_STATE(179)] = 1788,
  [SMALL_STATE(180)] = 1792,
  [SMALL_STATE(181)] = 1796,
  [SMALL_STATE(182)] = 1800,
  [SMALL_STATE(183)] = 1804,
  [SMALL_STATE(184)] = 1808,
  [SMALL_STATE(185)] = 1812,
  [SMALL_STATE(186)] = 1816,
  [SMALL_STATE(187)] = 1820,
  [SMALL_STATE(188)] = 1824,
  [SMALL_STATE(189)] = 1828,
  [SMALL_STATE(190)] = 1832,
  [SMALL_STATE(191)] = 1836,
  [SMALL_STATE(192)] = 1840,
  [SMALL_STATE(193)] = 1844,
  [SMALL_STATE(194)] = 1848,
  [SMALL_STATE(195)] = 1852,
  [SMALL_STATE(196)] = 1856,
  [SMALL_STATE(197)] = 1860,
  [SMALL_STATE(198)] = 1864,
  [SMALL_STATE(199)] = 1868,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(168),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(161),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(152),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(164),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(168),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_content, 2, 0, 0), SHIFT_REPEAT(7),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__block_content, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_content, 2, 0, 0), SHIFT_REPEAT(9),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_content, 2, 0, 0), SHIFT_REPEAT(143),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_type, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(166),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_type, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_type, 5, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 4),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 13),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 6, 0, 8),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 6, 0, 10),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 25),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 10, 0, 33),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface, 5, 0, 5),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 10, 0, 32),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 24),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 10, 0, 31),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 12),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 4, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 23),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 22),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 11, 0, 39),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 14),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__complex_type, 3, 0, 6),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 5, 0, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_type, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__complex_type, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 18),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 17),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(176),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 15),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 16),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(171),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface, 4, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 5, 0, 5),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 6, 0, 29),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 5, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 4, 0, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 5, 0, 20),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 5, 0, 21),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 4, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_methods, 1, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_parameters, 3, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_interface_methods_repeat1, 2, 0, 0),
  [270] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_interface_methods_repeat1, 2, 0, 0), SHIFT_REPEAT(149),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_members_repeat1, 2, 0, 0),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_members_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_members, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(172),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effekts, 4, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 2, 0, 11),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 5, 0, 30),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 7),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 6, 0, 38),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 6, 0, 28),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effekts, 5, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 6, 0, 27),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 7, 0, 37),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_members, 2, 0, 0),
  [322] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_effekts_repeat1, 2, 0, 0), SHIFT_REPEAT(172),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_effekts_repeat1, 2, 0, 0),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 3, 0, 0),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [335] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(155),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_parameters_repeat1, 2, 0, 0),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 4, 0, 0),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 5, 0, 19),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 9, 0, 43),
  [354] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 8, 0, 42),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 8, 0, 41),
  [358] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 8, 0, 40),
  [360] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_identifier, 1, 0, 0),
  [362] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_member, 3, 0, 9),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [374] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 7, 0, 36),
  [376] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 7, 0, 35),
  [378] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 7, 0, 34),
  [380] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_method, 6, 0, 26),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [390] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_member, 4, 0, 9),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [406] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [428] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(170),
  [432] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [436] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [438] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [440] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [442] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [444] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_effekt(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
